import { chromium, expect, test } from "@playwright/test";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

test("installed extension shares its private library with chat and remembers world bindings", async ({}, testInfo) => {
  test.skip(testInfo.project.name !== "chromium", "Chrome extension runtime scenario");
  test.setTimeout(90000);
  const profile = await mkdtemp(path.join(tmpdir(), "deeprole-extension-test-"));
  const extension = path.resolve(".output/chrome-mv3");
  const context = await chromium.launchPersistentContext(profile, { channel: "msedge", headless: true, args: [`--disable-extensions-except=${extension}`, `--load-extension=${extension}`] });
  context.setDefaultTimeout(10000);
  try {
    const worker = context.serviceWorkers()[0] ?? await context.waitForEvent("serviceworker", { timeout: 15000 });
    const extensionId = new URL(worker.url()).host;
    const html = '<!doctype html><html><head><title>Mock DeepSeek</title></head><body><main><header><h1>Test chat</h1></header><form><textarea aria-label="Message"></textarea><button type="submit">Send</button></form></main></body></html>';
    await context.route("https://chat.deepseek.com/**", (route) => route.fulfill({ contentType: "text/html", body: html }));
    const panel = await context.newPage();
    await panel.goto(`chrome-extension://${extensionId}/sidepanel.html`);
    await panel.evaluate(async () => { await (globalThis as any).chrome.storage.local.set({ deeprole_settings: { locale: "ru", onboardingComplete: true } }); });
    await panel.reload();
    await panel.getByRole("button", { name: "Лор", exact: true }).click();
    await panel.getByRole("button", { name: "Загрузить готовый лор", exact: true }).click();
    await panel.getByLabel("Выбрать JSON", { exact: true }).setInputFiles({ name: "Runtime World.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify({ "Runtime rule": { value: "Only this world", importance: "always" }, "Promise": { value: "A unique promise", importance: "called" } })) });
    await panel.getByRole("button", { name: "Подтвердить импорт", exact: true }).click();
    await expect(panel.getByRole("heading", { name: "Runtime World", exact: true })).toBeVisible();
    await panel.getByRole("button", { name: "Мир и профили", exact: true }).click();
    await panel.getByRole("button", { name: "Добавить профиль", exact: true }).click();
    await panel.getByRole("textbox", { name: "Название", exact: true }).fill("Мира");
    await panel.getByRole("checkbox", { name: /Promise/ }).check();
    await panel.getByRole("button", { name: "Сохранить", exact: true }).click();
    await expect(panel.getByRole("heading", { name: "Мира", exact: true })).toBeVisible();
    await panel.getByRole("button", { name: "Карта мира", exact: true }).click();
    await panel.getByRole("button", { name: "Список записей", exact: true }).click();
    await panel.locator(".memory-card").filter({ has: panel.getByRole("heading", { name: "Runtime rule", exact: true }) }).getByRole("button", { name: "Изменить", exact: true }).click();
    await panel.locator(".rp-entry-links summary").filter({ hasText: /^Связи с другими записями/ }).click();
    await panel.getByRole("checkbox", { name: "Promise", exact: true }).check();
    await panel.getByRole("textbox", { name: "Описание связи: Promise", exact: true }).fill("possible continuation");
    await panel.getByRole("combobox", { name: "Связи с другими записями: Promise", exact: true }).selectOption("reference");
    await panel.getByRole("button", { name: "Сохранить", exact: true }).click();
    await panel.getByRole("button", { name: "Мир и профили", exact: true }).click();
    await panel.getByRole("button", { name: "Создать заготовку", exact: true }).click();
    await panel.getByRole("textbox", { name: "Название", exact: true }).fill("Runtime starter");
    await panel.getByRole("textbox", { name: "Первая реплика", exact: true }).fill("Open the door.");
    await panel.getByRole("textbox", { name: "Исходное состояние сюжета", exact: true }).fill("Early morning.");
    await panel.getByRole("checkbox", { name: "Мира", exact: true }).check();
    await panel.getByRole("button", { name: "Сохранить", exact: true }).click();
    const chat = await context.newPage();
    await chat.goto("https://chat.deepseek.com/");
    const world = chat.getByRole("combobox", { name: "Мир", exact: true });
    await expect(world).toBeVisible();
    await world.selectOption({ label: "Runtime World" });
    await expect(chat.locator("html")).toHaveAttribute("data-deeprole-context", /Only this world/);
    await expect(chat.locator("html")).not.toHaveAttribute("data-deeprole-context", /unique promise/);
    await chat.getByRole("button", { name: /^Сцена/ }).click();
    await chat.getByRole("checkbox", { name: "Мира", exact: true }).check();
    await expect(chat.locator("html")).toHaveAttribute("data-deeprole-context", /unique promise/);
    let prompt = "";
    await context.route("https://chat.deepseek.com/api/v0/chat/completion", async (route) => { prompt = route.request().postDataJSON().prompt; await route.fulfill({ contentType: "application/json", body: "{}" }); });
    await chat.evaluate(() => fetch("/api/v0/chat/completion", { method: "POST", body: JSON.stringify({ prompt: "Hello" }) }));
    expect(prompt).toContain("A unique promise");
    expect(prompt).toContain('"Runtime rule" → "Promise": "possible continuation"');
    expect(prompt).toContain("[User message]\nHello");
    await expect(chat.getByRole("textbox", { name: "Message" })).toHaveValue("");
    // Simulate DeepSeek's SPA transition following the first send.
    await chat.evaluate(() => { history.pushState({}, "", "/chat/s/runtime-chat"); document.body.append(document.createElement("span")); });
    await expect.poll(async () => panel.evaluate(async () => {
      const api = (globalThis as any).chrome;
      const [tab] = await api.tabs.query({ url: "https://chat.deepseek.com/*" });
      const state = await api.tabs.sendMessage(tab.id, { type: "DR_GET_PAGE_STATE" });
      return state.chatId === "runtime-chat" && Boolean(state.scene.worldId);
    })).toBe(true);
    await chat.reload();
    await expect(world.locator("option:checked")).toHaveText("Runtime World");
    await expect(chat.locator("html")).toHaveAttribute("data-deeprole-context", /Only this world/);
    await world.selectOption("");
    await expect(chat.locator("html")).toHaveAttribute("data-deeprole-context", "");
    await chat.getByRole("button", { name: "Открыть меню DeepRole", exact: true }).click();
    await chat.frameLocator("iframe").getByRole("button", { name: "Закрыть", exact: true }).click();
    await expect(chat.locator("iframe")).toHaveCount(0);
    await chat.goto("https://chat.deepseek.com/");
    await chat.getByRole("button", { name: "Открыть меню DeepRole", exact: true }).click();
    const menu = chat.frameLocator("iframe");
    await menu.getByRole("button", { name: "Лор", exact: true }).click();
    await menu.getByRole("button", { name: /^Библиотека мира:/ }).click();
    await menu.getByRole("menuitemradio", { name: "Runtime World", exact: true }).click();
    await menu.getByRole("button", { name: "Мир и профили", exact: true }).click();
    await menu.getByRole("button", { name: "Карта мира", exact: true }).click();
    await menu.getByRole("button", { name: "Открыть карту мира", exact: true }).click();
    const map = menu.getByRole("dialog", { name: "Карта мира", exact: true });
    await expect(map).toBeVisible();
    await expect(chat.locator(".dr-menu-drawer")).toHaveClass(/map-compact/);
    const windowed = (await chat.locator("iframe").boundingBox())!;
    expect(windowed.width).toBeGreaterThan(400);
    await map.getByRole("button", { name: "Развернуть на весь экран", exact: true }).click();
    await expect(chat.locator(".dr-menu-drawer")).toHaveClass(/map-full/);
    const full = (await chat.locator("iframe").boundingBox())!;
    expect(full.width).toBe(chat.viewportSize()!.width - 24);
    // The outer iframe can resize one frame before its inner layout. Wait for
    // both surfaces before clicking a control whose page coordinates just moved.
    await expect.poll(() => map.evaluate(node => Math.round(node.getBoundingClientRect().width))).toBe(Math.round(full.width));
    await map.getByRole("button", { name: "Свернуть в окно", exact: true }).click();
    await expect(map).toHaveClass(/is-compact/);
    await expect(chat.locator(".dr-menu-drawer")).toHaveClass(/map-compact/);
    await menu.getByRole("textbox", { name: "Найти запись или ветвь…", exact: true }).focus();
    await chat.keyboard.press("Escape");
    await expect(map).toHaveCount(0);
    await expect(chat.locator("iframe")).toHaveCount(1);
    await expect(chat.locator(".dr-menu-drawer")).toHaveClass(/map-closed/);
    expect((await chat.locator("iframe").boundingBox())!.width).toBeLessThanOrEqual(400);
    await menu.getByRole("button", { name: "Мир и профили", exact: true }).click();
    await menu.getByRole("button", { name: "Подготовить в пустом чате", exact: true }).click();
    await expect(chat.getByRole("textbox", { name: "Message" })).toHaveValue("Open the door.\n\nEarly morning.");
    await expect(world.locator("option:checked")).toHaveText("Runtime World");
    await expect(chat.locator("html")).toHaveAttribute("data-deeprole-context", /unique promise/);
    await chat.screenshot({ path: testInfo.outputPath("installed-world-scene.png") });
    await menu.getByRole("button", { name: "Добавить профиль", exact: true }).click();
    await menu.getByRole("textbox", { name: "Название", exact: true }).fill("Рин");
    await menu.getByRole("button", { name: "Сохранить", exact: true }).click();
    await expect(menu.getByRole("heading", { name: "Рин", exact: true })).toBeVisible();
    await menu.getByRole("button", { name: "Закрыть", exact: true }).click();
    await chat.getByRole("button", { name: /^Сцена/ }).click();
    await expect(chat.getByRole("checkbox", { name: "Рин", exact: true })).toBeVisible();
  } finally { await context.close(); }
});
