import { chromium, expect, test } from "@playwright/test";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

test("installed extension shares its private library with chat and remembers world bindings", async ({}, testInfo) => {
  test.skip(testInfo.project.name !== "chromium", "Chrome extension runtime scenario");
  test.setTimeout(90000);
  const profile = await mkdtemp(path.join(tmpdir(), "deeprole-extension-test-"));
  const extension = path.resolve(process.env.DEEPROLE_TEST_BUILD ?? ".output/chrome-mv3");
  const context = await chromium.launchPersistentContext(profile, { channel: "msedge", headless: true, args: [`--disable-extensions-except=${extension}`, `--load-extension=${extension}`] });
  context.setDefaultTimeout(10000);
  try {
    const worker = context.serviceWorkers()[0] ?? await context.waitForEvent("serviceworker", { timeout: 15000 });
    const extensionId = new URL(worker.url()).host;
    const html = '<!doctype html><html><head><title>Mock DeepSeek</title></head><body><main><header><h1>Test chat</h1></header><form><textarea aria-label="Message"></textarea><button type="submit">Send</button></form></main></body></html>';
    await context.route("https://chat.deepseek.com/**", (route) => route.fulfill({ contentType: "text/html", body: html }));
    const panel = await context.newPage();
    await panel.goto(`chrome-extension://${extensionId}/sidepanel.html`);
    await panel.evaluate(async () => { await (globalThis as any).chrome.storage.local.set({ deeprole_settings: { locale: "ru", onboardingComplete: true } }); });
    await panel.reload();
    await panel.getByRole("button", { name: "Лор", exact: true }).click();
    await panel.getByRole("button", { name: "Загрузить готовый лор", exact: true }).click();
    await panel.getByLabel("Выбрать JSON", { exact: true }).setInputFiles({ name: "Runtime World.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify({ "Runtime rule": { value: "Only this world", importance: "always" }, "Promise": { value: "A unique promise", importance: "called" } })) });
    const confirmImport = panel.getByRole("button", { name: "Подтвердить импорт", exact: true });
    await expect(confirmImport).not.toHaveCSS("box-shadow", "none");
    expect(await confirmImport.evaluate(node => getComputedStyle(node).backgroundImage)).toContain("linear-gradient");
    expect(await confirmImport.evaluate(node => getComputedStyle(node, "::before").pointerEvents)).toBe("none");
    await confirmImport.click();
    await expect(panel.getByRole("heading", { name: "Runtime World", exact: true })).toBeVisible();
    await panel.getByRole("button", { name: "Мир и профили", exact: true }).click();
    await panel.getByRole("button", { name: "Добавить профиль", exact: true }).click();
    await panel.getByRole("textbox", { name: "Название", exact: true }).fill("Мира");
    await panel.getByRole("checkbox", { name: /Promise/ }).check();
    await panel.getByRole("button", { name: "Сохранить", exact: true }).click();
    await expect(panel.getByRole("heading", { name: "Мира", exact: true })).toBeVisible();
    await panel.getByRole("button", { name: "Карта мира", exact: true }).click();
    await panel.getByRole("button", { name: "Список записей", exact: true }).click();
    await panel.locator(".memory-card").filter({ has: panel.getByRole("heading", { name: "Runtime rule", exact: true }) }).getByRole("button", { name: "Изменить", exact: true }).click();
    await panel.locator(".rp-entry-links summary").filter({ hasText: /^Связи с другими записями/ }).click();
    await panel.getByRole("checkbox", { name: "Promise", exact: true }).check();
    await panel.getByRole("textbox", { name: "Описание связи: Promise", exact: true }).fill("possible continuation");
    await panel.getByRole("combobox", { name: "Связи с другими записями: Promise", exact: true }).selectOption("reference");
    await panel.getByRole("button", { name: "Сохранить", exact: true }).click();
    await panel.getByRole("button", { name: "Мир и профили", exact: true }).click();
    await panel.getByRole("button", { name: "Создать заготовку", exact: true }).click();
    await panel.getByRole("textbox", { name: "Название", exact: true }).fill("Runtime starter");
    await panel.getByRole("textbox", { name: "Первая реплика", exact: true }).fill("Open the door.");
    await panel.getByRole("textbox", { name: "Исходное состояние сюжета", exact: true }).fill("Early morning.");
    await panel.getByRole("checkbox", { name: "Мира", exact: true }).check();
    await panel.getByRole("button", { name: "Сохранить", exact: true }).click();
    const chat = await context.newPage();
    await chat.goto("https://chat.deepseek.com/");
    const world = chat.getByRole("combobox", { name: "Мир", exact: true });
    await expect(world).toBeVisible();
    // Exercise the actual branded popup in WXT's isolated content-script root.
    await world.click();
    const worldMenu = chat.locator(".dr-select-menu");
    await expect(worldMenu).toBeVisible();
    await worldMenu.getByRole("option", { name: "Runtime World", exact: true }).click();
    await expect(chat.locator("html")).toHaveAttribute("data-deeprole-context", /Only this world/);
    await expect(chat.locator("html")).not.toHaveAttribute("data-deeprole-context", /unique promise/);
    await chat.getByRole("button", { name: /^Сцена/ }).click();
    await chat.getByRole("checkbox", { name: "Мира", exact: true }).check();
    await expect(chat.locator("html")).toHaveAttribute("data-deeprole-context", /unique promise/);
    let prompt = "";
    await context.route("https://chat.deepseek.com/api/v0/chat/completion", async (route) => { prompt = route.request().postDataJSON().prompt; await route.fulfill({ contentType: "application/json", body: "{}" }); });
    await chat.evaluate(() => fetch("/api/v0/chat/completion", { method: "POST", body: JSON.stringify({ prompt: "Hello" }) }));
    expect(prompt).toContain("A unique promise");
    expect(prompt).toContain('"Runtime rule" → "Promise": "possible continuation"');
    expect(prompt).toContain("[User message]\nHello");
    await expect(chat.getByRole("textbox", { name: "Message" })).toHaveValue("");
    // Simulate DeepSeek's SPA transition following the first send.
    await chat.evaluate(() => { history.pushState({}, "", "/chat/s/runtime-chat"); document.body.append(document.createElement("span")); });
    await expect.poll(async () => panel.evaluate(async () => {
      const api = (globalThis as any).chrome;
      const [tab] = await api.tabs.query({ url: "https://chat.deepseek.com/*" });
      const state = await api.tabs.sendMessage(tab.id, { type: "DR_GET_PAGE_STATE" });
      return state.chatId === "runtime-chat" && Boolean(state.scene.worldId);
    })).toBe(true);
    await chat.reload();
    await expect(world.locator("option:checked")).toHaveText("Runtime World");
    await expect(chat.locator("html")).toHaveAttribute("data-deeprole-context", /Only this world/);
    // Exercise the new additive emotion request through the real background,
    // not just a React fixture. This profile contains only synthetic data.
    await chat.locator(".dr-character-row").filter({ hasText: "Мира" }).click();
    const character = chat.getByRole("dialog");
    await character.getByRole("tab", { name: "Изображения", exact: true }).click();
    await character.locator("summary").filter({ hasText: /^Добавить эмоцию$/ }).click();
    await character.getByLabel("Название новой эмоции", { exact: true }).fill("Focused");
    await character.getByRole("button", { name: "Добавить эмоцию", exact: true }).click();
    await expect(character.getByLabel("Эмоция портрета", { exact: true })).toHaveValue("Focused");
    await character.getByRole("button", { name: "Закрыть", exact: true }).first().click();
    await chat.reload();
    await chat.locator(".dr-character-row").filter({ hasText: "Мира" }).click();
    await character.getByRole("tab", { name: "Изображения", exact: true }).click();
    await expect(character.getByLabel("Эмоция портрета", { exact: true }).locator('option[value="Focused"]')).toHaveCount(1);
    await character.getByRole("button", { name: "Закрыть", exact: true }).first().click();
    await chat.getByRole("button", { name: "Ширина всех панелей", exact: true }).click();
    await chat.getByRole("slider", { name: "Ширина всех панелей", exact: true }).press("End");
    await expect.poll(async () => panel.evaluate(async () => (await (globalThis as any).chrome.storage.local.get("deeprole_settings")).deeprole_settings.floatingPanelWidth)).toBe(360);
    await chat.getByRole("slider").press("Escape");
    await world.selectOption("");
    await expect(chat.locator("html")).toHaveAttribute("data-deeprole-context", "");
    await chat.getByRole("button", { name: "Открыть меню DeepRole", exact: true }).click();
    await chat.frameLocator("iframe").getByRole("button", { name: "Закрыть", exact: true }).click();
    await expect(chat.locator("iframe")).toHaveCount(0);
    await chat.goto("https://chat.deepseek.com/");
    await chat.getByRole("button", { name: "Открыть меню DeepRole", exact: true }).click();
    const menu = chat.frameLocator("iframe");
    await menu.getByRole("button", { name: "Лор", exact: true }).click();
    await menu.getByRole("button", { name: /^Библиотека мира:/ }).click();
    await menu.getByRole("menuitemradio", { name: "Runtime World", exact: true }).click();
    await menu.getByRole("button", { name: "Мир и профили", exact: true }).click();
    await menu.getByRole("button", { name: "Карта мира", exact: true }).click();
    await menu.getByRole("button", { name: "Открыть карту мира", exact: true }).click();
    const map = menu.getByRole("dialog", { name: "Карта мира", exact: true });
    await expect(map).toBeVisible();
    await expect(chat.locator(".dr-menu-drawer")).toHaveClass(/map-compact/);
    const windowed = (await chat.locator("iframe").boundingBox())!;
    expect(windowed.width).toBeGreaterThan(400);
    await map.getByRole("button", { name: "Развернуть на весь экран", exact: true }).click();
    await expect(chat.locator(".dr-menu-drawer")).toHaveClass(/map-full/);
    const full = (await chat.locator("iframe").boundingBox())!;
    expect(full.width).toBe(chat.viewportSize()!.width - 24);
    // The outer iframe can resize one frame before its inner layout. Wait for
    // both surfaces before clicking a control whose page coordinates just moved.
    await expect.poll(() => map.evaluate(node => Math.round(node.getBoundingClientRect().width))).toBe(Math.round(full.width));
    await map.getByRole("button", { name: "Свернуть в окно", exact: true }).click();
    await expect(map).toHaveClass(/is-compact/);
    await expect(chat.locator(".dr-menu-drawer")).toHaveClass(/map-compact/);
    await menu.getByRole("textbox", { name: "Найти запись или ветвь…", exact: true }).focus();
    await chat.keyboard.press("Escape");
    await expect(map).toHaveCount(0);
    await expect(chat.locator("iframe")).toHaveCount(1);
    await expect(chat.locator(".dr-menu-drawer")).toHaveClass(/map-closed/);
    expect((await chat.locator("iframe").boundingBox())!.width).toBeLessThanOrEqual(400);
    await menu.getByRole("button", { name: "Мир и профили", exact: true }).click();
    await menu.getByRole("button", { name: "Подготовить в пустом чате", exact: true }).click();
    await expect(chat.getByRole("textbox", { name: "Message" })).toHaveValue("Open the door.\n\nEarly morning.");
    await expect(world.locator("option:checked")).toHaveText("Runtime World");
    await expect(chat.locator("html")).toHaveAttribute("data-deeprole-context", /unique promise/);
    await chat.screenshot({ path: testInfo.outputPath("installed-world-scene.png") });
    await menu.getByRole("button", { name: "Добавить профиль", exact: true }).click();
    await menu.getByRole("textbox", { name: "Название", exact: true }).fill("Рин");
    await menu.getByRole("button", { name: "Сохранить", exact: true }).click();
    await expect(menu.getByRole("heading", { name: "Рин", exact: true })).toBeVisible();
    await menu.getByRole("button", { name: "Закрыть", exact: true }).click();
    await chat.getByRole("button", { name: /^Сцена/ }).click();
    await expect(chat.getByRole("checkbox", { name: "Рин", exact: true })).toBeVisible();
  } finally { await context.close(); }
});

test("installed pinned options follow the native message panel without changing its draft", async ({}, testInfo) => {
  test.skip(testInfo.project.name !== "chromium", "Chrome extension runtime scenario");
  test.setTimeout(60000);
  const profile = await mkdtemp(path.join(tmpdir(), "deeprole-pinned-runtime-"));
  const extension = path.resolve(process.env.DEEPROLE_TEST_BUILD ?? ".output/chrome-mv3");
  const context = await chromium.launchPersistentContext(profile, { channel: "msedge", headless: true, viewport: { width: 1500, height: 850 }, args: [`--disable-extensions-except=${extension}`, `--load-extension=${extension}`] });
  try {
    const worker = context.serviceWorkers()[0] ?? await context.waitForEvent("serviceworker", { timeout: 15000 });
    const extensionId = new URL(worker.url()).host;
    const panel = await context.newPage();
    await panel.goto(`chrome-extension://${extensionId}/sidepanel.html`);
    await panel.evaluate(async () => { await (globalThis as any).chrome.storage.local.set({ deeprole_settings: { locale: "en", onboardingComplete: true, adaptiveLayout: true } }); });
    const options = ["positive", "neutral", "negative", "surprise"].map((kind, i) => ({ kind, label: `Move ${i}`, text: `I choose move ${i}.` }));
    const html = `<!doctype html><html><head><title>Mock DeepSeek</title><style>body{margin:0;background:#181818;color:#eee;font:15px system-ui}aside{position:fixed;inset:0 auto 0 0;width:264px;background:#242424;transition:transform .3s ease}header h1{position:fixed;left:280px;top:20px;margin:0;font-size:16px;transition:left .3s ease}.sidebar-closed aside{transform:translateX(-264px)}.sidebar-closed header h1{left:194px}main{max-width:680px;margin:100px auto;min-height:2000px}form{position:fixed;left:330px;bottom:20px;width:680px;padding:12px;border-radius:20px;background:#303030;box-sizing:border-box}textarea{width:100%;height:80px;box-sizing:border-box}form>button{margin-top:8px}</style></head><body><aside><a href="/chat/s/pinned-runtime">Test chat</a></aside><main><header><h1>Test chat</h1></header><article data-message-id="scene" data-role="assistant"><div class="ds-markdown">Mira waits.&lt;deeprole_choices&gt;${JSON.stringify({ version: 1, options })}&lt;/deeprole_choices&gt;</div></article></main><form><textarea aria-label="Message"></textarea><button type="submit">Send</button></form></body></html>`;
    await context.route("https://chat.deepseek.com/**", route => route.fulfill({ contentType: "text/html", body: html }));
    const chat = await context.newPage();
    await chat.goto("https://chat.deepseek.com/chat/s/pinned-runtime");
    const host = chat.locator("[data-deeprole-choices-host]");
    await expect(host).toBeVisible();
    await host.getByRole("button", { name: "Pin options on screen", exact: true }).click();
    await expect.poll(async () => panel.evaluate(async () => (await (globalThis as any).chrome.storage.local.get("deeprole_settings")).deeprole_settings.pinSceneChoices)).toBe(true);
    const aligned = async () => {
      const geometry = await host.evaluate(node => {
        const card = node.shadowRoot!.querySelector("section")!.getBoundingClientRect(), form = document.querySelector("form")!.getBoundingClientRect();
        return { center: card.left + card.width / 2, formCenter: form.left + form.width / 2, gap: form.top - card.bottom, inBody: node.parentElement === document.body };
      });
      expect(geometry.inBody).toBe(true);
      expect(geometry.center).toBeCloseTo(geometry.formCenter, 0);
      expect(geometry.gap).toBeCloseTo(12, 0);
    };
    await expect.poll(async () => { try { await aligned(); return true; } catch { return false; } }).toBe(true);
    await chat.getByRole("textbox", { name: "Message", exact: true }).fill("My personal draft remains untouched.");
    const dock = chat.locator(".dr-widget-dock");
    await expect.poll(async () => (await dock.boundingBox())!.x).toBeCloseTo(272, 0);
    const layoutBefore = await panel.evaluate(async () => (await (globalThis as any).chrome.storage.local.get("deeprole.widgetLayout.v1"))["deeprole.widgetLayout.v1"] ?? null);
    await chat.evaluate(() => document.body.classList.add("sidebar-closed"));
    await expect.poll(async () => (await dock.boundingBox())!.x).toBeCloseTo(8, 0);
    expect(await panel.evaluate(async () => (await (globalThis as any).chrome.storage.local.get("deeprole.widgetLayout.v1"))["deeprole.widgetLayout.v1"] ?? null)).toEqual(layoutBefore);
    await expect.poll(async () => { try { await aligned(); return true; } catch { return false; } }).toBe(true);
    await chat.evaluate(() => { window.scrollTo(0, 900); (document.querySelector("textarea") as HTMLElement).style.height = "200px"; });
    await expect.poll(async () => { try { await aligned(); return true; } catch { return false; } }).toBe(true);
    await chat.setViewportSize({ width: 640, height: 760 });
    await chat.evaluate(() => Object.assign(document.querySelector("form")!.style, { left: "20px", width: "calc(100% - 40px)" }));
    await expect.poll(async () => { try { await aligned(); return true; } catch { return false; } }).toBe(true);
    await expect(chat.getByRole("textbox", { name: "Message", exact: true })).toHaveValue("My personal draft remains untouched.");
    await chat.screenshot({ path: testInfo.outputPath("installed-pinned-above-composer.png") });
    await chat.evaluate(() => Object.assign(document.querySelector("main")!.style, { minHeight: "0", paddingTop: "1000px" }));
    const beforeUnpin = await chat.evaluate(() => window.scrollY);
    await host.getByRole("button", { name: "Unpin options", exact: true }).click();
    await expect.poll(async () => panel.evaluate(async () => (await (globalThis as any).chrome.storage.local.get("deeprole_settings")).deeprole_settings.pinSceneChoices)).toBe(false);
    await expect.poll(() => host.evaluate(node => node.parentElement !== document.body)).toBe(true);
    await expect.poll(() => chat.evaluate(() => window.scrollY)).toBeCloseTo(beforeUnpin, 0);
    // Wait for the actual unpin before simulating the reader's next scroll.
    await chat.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight));

    await expect.poll(() => host.evaluate(node => {
      const card = node.shadowRoot!.querySelector("section")!.getBoundingClientRect(), form = document.querySelector("form")!.getBoundingClientRect();
      return node.parentElement !== document.body && form.top - card.bottom >= 11 && Math.abs(card.left + card.width / 2 - form.left - form.width / 2) < 1;
    })).toBe(true);
    const inlineY = (await host.boundingBox())!.y;
    await chat.evaluate(() => window.scrollTo(0, 0));
    await expect.poll(async () => (await host.boundingBox())!.y).toBeGreaterThan(inlineY + 200);
    await chat.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight));
    await expect.poll(() => host.evaluate(node => document.querySelector("form")!.getBoundingClientRect().top - node.shadowRoot!.querySelector("section")!.getBoundingClientRect().bottom)).toBeGreaterThanOrEqual(11);
    await expect(chat.getByRole("textbox", { name: "Message", exact: true })).toHaveValue("My personal draft remains untouched.");
    await chat.screenshot({ path: testInfo.outputPath("installed-inline-above-composer.png") });
  } finally { await context.close(); }
});
