import { chromium, expect, test } from "@playwright/test";
import { mkdir, mkdtemp } from "node:fs/promises";
import path from "node:path";

test("installed portrait constructor preserves multi-speaker scenes, lore and chat scope", async ({}, info) => {
  test.skip(info.project.name !== "chromium", "Chrome MV3 installed bridge; shared UI is tested in Firefox"); test.setTimeout(90000);
  const profiles = path.join(info.project.outputDir, "profiles"); await mkdir(profiles, { recursive: true });
  const profile = await mkdtemp(path.join(profiles, "deeprole-portrait-test-"));
  const context = await chromium.launchPersistentContext(profile, { channel: "msedge", headless: true, args: [`--disable-extensions-except=${path.resolve(".output/chrome-mv3")}`, `--load-extension=${path.resolve(".output/chrome-mv3")}`] });
  try {
    context.setDefaultTimeout(10000);
    const worker = context.serviceWorkers()[0] ?? await context.waitForEvent("serviceworker");
    await context.route("https://chat.deepseek.com/**", route => route.fulfill({ contentType: "text/html", body: '<!doctype html><html lang="en"><head><title>Portrait test</title></head><body><main><h1>Test observatory</h1><div id="conversation"></div><form><textarea aria-label="Message"></textarea><button type="submit">Send</button></form></main></body></html>' }));
    const panel = await context.newPage(); await panel.goto(`chrome-extension://${new URL(worker.url()).host}/sidepanel.html`);
    // Wait for the repository schema: page navigation alone doesn't initialize IndexedDB.
    await expect(panel.locator(".onboarding")).toBeVisible();
    const variations = await panel.evaluate(() => ["#486db0", "#84b79c"].map(color => { const canvas = document.createElement("canvas"); canvas.width = 12; canvas.height = 16; const ctx = canvas.getContext("2d")!; ctx.fillStyle = color; ctx.fillRect(0, 0, 12, 16); return canvas.toDataURL("image/png"); }));
    const state = { emotion: "neutral", condition: "Safe", goal: "Find the key", relationship: "", stats: [{ label: "Energy", value: "Rested" }] };
    const people = ["Noah", "Mira", "Leon", "Guard"].map((name, index) => ({ id: name.toLowerCase(), worldId: "w", name, kind: "character", description: "ORIGINAL", aliases: [], memberIds: [], characterSheet: { gender: "neutral", protagonist: index === 0, appearance: "", personality: "", goals: "", background: "", sprites: {} }, createdAt: 1, updatedAt: 1 }));
    people[1]!.characterSheet.sprites = { neutral: variations };
    people[2]!.characterSheet.sprites = Object.fromEntries(["neutral", "retired-mood", ...Array.from({ length: 10 }, (_, i) => `mood-${i}`)].map(name => [name, variations]));
    const emotions = ["neutral", "happy", "worried", ...Array.from({ length: 29 }, (_, i) => `emotion-${i}`)];
    const initial = { revision: "v", presentIds: people.map(p => p.id), partnerIds: ["mira", "leon"], partnerId: "mira", states: Object.fromEntries(people.map(p => [p.id, state])), updatedAt: 1 };
    const binding = { id: "binding:a", chatId: "a", chatUrl: "https://chat.deepseek.com/chat/s/a", worldId: "w", bookId: null, focusIds: [], messageCountAtAnalysis: 0, characterScenes: { w: initial }, createdAt: 1, updatedAt: 1 };
    await panel.evaluate(async rows => {
      await new Promise<void>((resolve, reject) => { const open = indexedDB.open("deeprole"); open.onerror = () => reject(open.error); open.onsuccess = () => { const db = open.result; const tx = db.transaction("records", "readwrite"); for (const [kind, data] of rows) tx.objectStore("records").put({ pk: `${kind}:${data.id}`, kind, id: data.id, data, updatedAt: 1 }); tx.oncomplete = () => { db.close(); resolve(); }; tx.onerror = () => reject(tx.error); }; });
      await (window as any).chrome.storage.local.set({ deeprole_settings: { locale: "en", onboardingComplete: true, characterSheetsEnabled: true, portraitLayoutResetAt: 0 } });
    }, [["world", { id: "w", name: "Observatory", description: "", color: "#58a6ff", contextBudget: 3000, relevanceThreshold: 6, characterEmotions: emotions, createdAt: 1, updatedAt: 1 }], ...people.map(p => ["entity", p]), ["binding", binding], ["binding", { ...binding, id: "binding:b", chatId: "b", chatUrl: "https://chat.deepseek.com/chat/s/b", characterScenes: {} }]] as Array<[string, any]>);
    const records = () => panel.evaluate(() => new Promise<any[]>(resolve => { const open = indexedDB.open("deeprole"); open.onsuccess = () => { const db = open.result; const request = db.transaction("records").objectStore("records").getAll(); request.onsuccess = () => { resolve(request.result); db.close(); }; }; }));
    const chat = await context.newPage(); await chat.goto(binding.chatUrl); await expect(chat.locator(".dr-character-row")).toHaveCount(4);
    await expect.poll(async () => { const rect = (await chat.locator('[data-widget="scene"]').boundingBox())!; return Math.round(rect.y + rect.height); }).toBeLessThanOrEqual(720);
    const append = (payload?: any) => chat.evaluate(payload => { const row = document.createElement("article"); row.dataset.role = "assistant"; row.dataset.messageId = "scene"; const options = ["positive", "neutral", "negative", "surprise"].map(kind => ({ kind, label: kind, text: "Ask about the key." })); row.textContent = "Mira, Leon and the guard stay in the observatory.\n" + (payload ? `<deeprole_characters>${JSON.stringify(payload)}</deeprole_characters>\n` : "") + `<deeprole_choices>${JSON.stringify({ version: 1, options })}</deeprole_choices>`; document.querySelector("#conversation")!.replaceChildren(row); }, payload);
    await append(); await expect(chat.locator(".dr-cast-widget")).toHaveCount(4); await expect(chat.locator('.dr-cast-widget[data-talking="true"]')).toHaveCount(2);
    const mira = chat.locator('.dr-cast-widget[data-character-id="mira"]'); const handle = mira.locator(".dr-cast-move");
    await expect(mira.locator("img")).toHaveAttribute("src", variations[0]!);
    await handle.scrollIntoViewIfNeeded(); const box = (await handle.boundingBox())!; await chat.mouse.move(box.x + 50, box.y + 20); await chat.mouse.down(); await chat.mouse.move(box.x - 100, box.y + 90, { steps: 6 }); await chat.mouse.up();
    await expect.poll(async () => (await records()).find(r => r.id === binding.id).data.portraitLayouts?.w?.positions?.mira?.y).toBeGreaterThan(0);
    const before = await records(); expect(before.find(r => r.id === binding.id).data.characterScenes.w).toEqual(initial); const savedPose = before.find(r => r.id === binding.id).data.portraitLayouts.w.positions.mira;
    await chat.reload(); await append(); await expect(mira).toHaveCSS("position", "absolute");
    let schema: any; const prompts: string[] = [];
    await context.route("https://chat.deepseek.com/api/v0/chat/completion", route => { const prompt = route.request().postDataJSON().prompt; prompts.push(prompt); schema = JSON.parse(prompt.match(/Schema: (.*)\nRoster:/)[1]); return route.fulfill({ contentType: "application/json", body: "{}" }); });
    await chat.evaluate(() => fetch("/api/v0/chat/completion", { method: "POST", body: JSON.stringify({ prompt: "Leon addresses Noah. Mira stays beside the guard." }) }));
    expect(schema.partners).toEqual([]); expect(prompts[0]).toContain("A change of addressee is not a departure"); expect(prompts[0]).not.toContain("portraitLayouts");
    const payload = { request: schema.request, present: people.map(p => p.name), partners: ["Leon"], updates: [{ id: "Leon", name: "Leon", state: { ...state, emotion: "worried" } }] };
    await append(payload); await expect(chat.locator(".dr-character-status")).toHaveText("Updated after reply");
    await expect(mira.locator("img")).toHaveAttribute("src", variations[1]!);
    expect(prompts[0]).not.toContain("base64"); expect(prompts[0]).not.toContain("portraitCycles");
    await expect(chat.locator(".dr-cast-widget")).toHaveCount(4); await expect(chat.locator('.dr-cast-widget[data-talking="true"]')).toHaveCount(1); await expect(chat.locator('.dr-cast-widget[data-character-id="leon"] small')).toHaveText("Worried");
    expect((await records()).find(r => r.id === binding.id).data.portraitLayouts.w.positions.mira).toEqual(savedPose);
    await mira.locator(".dr-cast-portrait").focus(); await mira.locator(".dr-cast-portrait").press("Enter"); const dialog = chat.getByRole("dialog"); const partner = dialog.getByRole("checkbox", { name: "Talking to the protagonist", exact: true });
    await expect(partner).not.toBeChecked(); await partner.check(); await dialog.getByRole("button", { name: "Save character", exact: true }).click();
    await expect(chat.locator('.dr-cast-widget[data-talking="true"]')).toHaveCount(2);
    const saved = await records(); let current = saved.find(r => r.id === binding.id).data;
    expect(current.characterScenes.w.partnerIds).toEqual(["mira", "leon"]); expect(current.characterScenes.w.presentIds).toHaveLength(4);
    expect(saved.filter(r => r.kind === "entity").map(r => r.data)).toEqual(expect.arrayContaining(people.map(p => expect.objectContaining({ id: p.id, description: "ORIGINAL", characterSheet: p.characterSheet }))));
    await expect(chat.locator(".dr-characters img")).toHaveCount(0);
    await chat.getByRole("button", { name: "Open character gallery", exact: true }).click();
    const gallery = chat.getByRole("dialog"); await expect(gallery.locator(".dr-character-gallery-card")).toHaveCount(4);
    await gallery.evaluate(node => { (window as any).galleryNode = node; });
    await gallery.getByRole("button", { name: "Edit character: Leon", exact: true }).click();
    await expect(gallery).toHaveCount(1); expect(await gallery.evaluate(node => node === (window as any).galleryNode)).toBe(true);
    await chat.screenshot({ path: info.outputPath("installed-gallery-editor.png") });
    await expect(gallery.getByLabel("Name", { exact: true })).toHaveValue("Leon");
    await gallery.getByLabel("Condition", { exact: true }).fill("At the telescope.");
    await gallery.getByRole("button", { name: "Save character", exact: true }).click();
    await expect(gallery.locator(".dr-character-gallery-view")).toBeVisible();
    await expect.poll(async () => (await records()).find(r => r.id === binding.id).data.characterScenes.w.states.leon.condition).toBe("At the telescope.");
    current = (await records()).find(r => r.id === binding.id).data;
    expect(current.characterScenes.w.states.leon.condition).toBe("At the telescope.");
    expect(current.portraitLayouts.w.positions.mira).toEqual(savedPose);
    await chat.keyboard.press("Escape"); await expect(gallery).toHaveCount(0);
    await chat.screenshot({ path: info.outputPath("installed-multi-portraits.png") });
    await chat.goto("https://chat.deepseek.com/chat/s/b"); await expect(chat.locator(".dr-character-row")).toHaveCount(4); await append(); await expect(chat.locator(".dr-cast-widget")).toHaveCount(1);
    expect((await records()).find(r => r.id === "binding:b").data.portraitLayouts).toBeUndefined();
    await chat.goto(binding.chatUrl); await append(payload); await expect(mira).toHaveCSS("position", "absolute"); await expect(chat.locator(".dr-character-status")).toHaveText("Updated after reply");
    expect((await records()).find(r => r.id === binding.id).data.characterScenes.w).toEqual(current.characterScenes.w); expect(prompts).toHaveLength(1);
    await expect(mira.locator("img")).toHaveAttribute("src", variations[1]!);
    await chat.locator('[data-widget="characters"]').hover();
    await chat.getByRole("button", { name: "Minimize: Characters", exact: true }).click();
    await expect(chat.locator('[data-restore-widget="characters"]')).toBeVisible();
    await chat.reload(); await expect(chat.locator('[data-restore-widget="characters"]')).toBeVisible();
    await expect(chat.locator(".dr-characters")).toBeHidden();
    await chat.locator('[data-restore-widget="characters"]').click(); await expect(chat.locator(".dr-character-row")).toHaveCount(4);
    // A new protagonist must accept emotion images in the same save, and again after reopening.
    await chat.locator(".dr-character-row").filter({ hasText: "Leon" }).click();
    await dialog.getByRole("checkbox", { name: "My protagonist", exact: true }).check();
    await dialog.getByLabel("Portrait emotion", { exact: true }).selectOption("happy");
    await dialog.locator('input[type=file]').setInputFiles({ name: "hero.png", mimeType: "image/png", buffer: Buffer.from(variations[0]!.split(",")[1]!, "base64") });
    await expect(dialog.locator(".dr-portrait-variations img")).toHaveCount(1);
    // A reply can finish while the portrait picker/editor is open.
    await chat.evaluate(() => fetch("/api/v0/chat/completion", { method: "POST", body: JSON.stringify({ prompt: "Leon notices the telescope is unlocked." }) }));
    await append({ request: schema.request, present: people.map(p => p.name), partners: ["Mira"], updates: [{ id: "Leon", name: "Leon", state: { ...state, emotion: "happy", goal: "Open the telescope" } }] });
    await expect.poll(async () => (await records()).find(r => r.id === binding.id).data.characterScenes.w.states.leon.goal).toBe("Open the telescope");
    await dialog.getByRole("button", { name: "Save character", exact: true }).click();
    await expect(dialog).toHaveCount(0);
    let hero = (await records()).find(r => r.id === "leon").data;
    expect(hero.characterSheet.protagonist).toBe(true);
    expect(hero.characterSheet.sprites.happy).toHaveLength(1);
    expect(Object.keys(hero.characterSheet.sprites)).toHaveLength(13);
    expect(hero.characterSheet.sprites["retired-mood"]).toEqual(variations);
    expect((await records()).find(r => r.id === binding.id).data.characterScenes.w.states.leon.goal).toBe("Open the telescope");
    await chat.locator(".dr-character-row").filter({ hasText: "Leon" }).click();
    await dialog.getByLabel("Portrait emotion", { exact: true }).selectOption("happy");
    await dialog.locator('input[type=file]').setInputFiles({ name: "hero2.png", mimeType: "image/png", buffer: Buffer.from(variations[1]!.split(",")[1]!, "base64") });
    await expect(dialog.locator(".dr-portrait-variations img")).toHaveCount(2);
    await chat.screenshot({ path: info.outputPath("protagonist-emotion-portraits.png") });
    await dialog.getByRole("button", { name: "Save character", exact: true }).click();
    await expect(dialog).toHaveCount(0);
    hero = (await records()).find(r => r.id === "leon").data;
    expect(hero.characterSheet.sprites.happy).toHaveLength(2);
    expect((await records()).filter(r => r.kind === "entity" && r.data.characterSheet.protagonist).map(r => r.id)).toEqual(["leon"]);
    await chat.reload(); await append();
    await expect(chat.locator('.dr-cast-widget[data-character-id="leon"] img')).toHaveAttribute("src", new RegExp("^data:image/"));
    await chat.locator(".dr-character-row").filter({ hasText: "Leon" }).click();
    await expect(dialog.getByRole("checkbox", { name: "My protagonist", exact: true })).toBeChecked();
    await dialog.getByLabel("Portrait emotion", { exact: true }).selectOption("happy");
    await expect(dialog.locator(".dr-portrait-variations img")).toHaveCount(2);
    await expect(dialog.getByLabel("Current goal", { exact: true })).toHaveValue("Open the telescope");
    await expect(dialog.getByLabel("Mood", { exact: true }).locator("option")).toHaveCount(32);
    await dialog.getByLabel("Portrait emotion", { exact: true }).selectOption("retired-mood");
    await expect(dialog.locator(".dr-portrait-variations img")).toHaveCount(2);
    await dialog.getByRole("button", { name: "Close", exact: true }).first().click();
    await chat.evaluate(() => fetch("/api/v0/chat/completion", { method: "POST", body: JSON.stringify({ prompt: "Leon studies the stars." }) }));
    expect(prompts.at(-1)).toContain(emotions[31]!);
    expect(prompts.at(-1)).not.toContain("retired-mood");
    await append({ request: schema.request, present: people.map(p => p.name), partners: ["Mira"], updates: [{ id: "Leon", name: "Leon", state: { ...state, emotion: emotions[31] } }] });
    await expect.poll(async () => (await records()).find(r => r.id === binding.id).data.characterScenes.w.states.leon.emotion).toBe(emotions[31]);
    // Bulk images are persisted locally before any emotion is assigned.
    const inbox = await chat.evaluate(() => ["#934156", "#976319", "#387784"].map(color => {
      const canvas = document.createElement("canvas"); canvas.width = 90; canvas.height = 120; const ctx = canvas.getContext("2d")!;
      ctx.fillStyle = color; ctx.fillRect(0, 0, 90, 120); return canvas.toDataURL("image/png").split(",")[1]!;
    }));
    await chat.locator(".dr-character-row").filter({ hasText: "Leon" }).click();
    await dialog.getByRole("button", { name: /^Image library ·/ }).click();
    const library = dialog.locator(".dr-portrait-library");
    await library.locator('input[type=file]').setInputFiles(inbox.map((image, i) => ({ name: `inbox-${i}.png`, mimeType: "image/png", buffer: Buffer.from(image, "base64") })));
    await expect(library.locator(".dr-library-image")).toHaveCount(3);
    await dialog.getByRole("button", { name: "Save character", exact: true }).click(); await expect(dialog).toHaveCount(0);
    expect((await records()).find(r => r.id === "leon").data.characterSheet.portraitLibrary).toHaveLength(3);
    await chat.reload(); await chat.locator(".dr-character-row").filter({ hasText: "Leon" }).click();
    await dialog.getByRole("button", { name: /^Image library ·/ }).click();
    await library.getByRole("button", { name: /^Unassigned ·/ }).click(); await expect(library.locator(".dr-library-image")).toHaveCount(3);
    for (let i = 0; i < 3; i++) await library.locator(".dr-library-image").nth(i).click();
    await library.locator("select").selectOption(emotions[31]!);
    await library.getByRole("button", { name: "Assign to emotion", exact: true }).click();
    await expect(dialog.locator(".dr-portrait-variations img")).toHaveCount(3);
    await chat.screenshot({ path: info.outputPath("installed-portrait-library.png") });
    await dialog.getByRole("button", { name: "Save character", exact: true }).click(); await expect(dialog).toHaveCount(0);
    hero = (await records()).find(r => r.id === "leon").data;
    expect(hero.characterSheet.portraitLibrary).toBeUndefined(); expect(hero.characterSheet.sprites[emotions[31]!]).toHaveLength(3);
    await chat.reload(); await expect(chat.locator(".dr-character-row")).toHaveCount(4);
    await chat.evaluate(() => fetch("/api/v0/chat/completion", { method: "POST", body: JSON.stringify({ prompt: "Leon looks through the telescope." }) }));
    expect(prompts.at(-1)).not.toContain("portraitLibrary"); expect(prompts.at(-1)).not.toContain("data:image");
    expect((await records()).find(r => r.id === "leon").data.characterSheet.sprites[emotions[31]!]).toEqual(hero.characterSheet.sprites[emotions[31]!]);
  } finally { await context.close(); }
});
