import { expect, test } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { setEnglish } from "./helpers/settings";

for (const locale of ["ru", "en"] as const) test(`opens a centered lore-import window and previews dropped files (${locale})`, async ({ page }) => {
  await page.setViewportSize({ width: 420, height: 900 });
  await page.goto("/tests/fixtures/sidepanel.html");
  if (locale === "en") {
    await page.getByRole("button", { name: "Настройки", exact: true }).click();
    await setEnglish(page);
  }
  const l = (ru: string, en: string) => locale === "ru" ? ru : en;
  await page.getByRole("button", { name: l("Лор", "Lore"), exact: true }).click();
  await page.getByRole("button", { name: l("Загрузить готовый лор", "Import existing lore"), exact: true }).click();
  const importDialog = page.getByRole("dialog", { name: l("Добавить из файла", "Add from file"), exact: true });
  await expect(importDialog).toBeVisible();
  const dialogBox = await importDialog.boundingBox(); const viewport = page.viewportSize()!;
  expect(Math.abs(dialogBox!.x + dialogBox!.width / 2 - viewport.width / 2)).toBeLessThan(2);
  expect(Math.abs(dialogBox!.y + dialogBox!.height / 2 - viewport.height / 2)).toBeLessThan(2);
  const dropzone = page.locator(".rp-import-dropzone");
  await expect(dropzone).toContainText(l("Перетащите сюда файл лора", "Drop your lore file here"));
  const transfer = await page.evaluateHandle((json) => { const value = new DataTransfer(); value.items.add(new File([json], "Тестовый мир.json", { type: "application/json" })); return value; }, JSON.stringify({ name: "Тестовый мир", entries: [{ title: "Правило", content: "Сохранить", activation: "always" }] }));
  await dropzone.dispatchEvent("dragenter", { dataTransfer: transfer });
  await expect(dropzone).toHaveClass(/is-dragging/);
  await dropzone.dispatchEvent("drop", { dataTransfer: transfer });
  await expect(page.getByText(l("Распознаны записи JSON", "JSON entries recognized"), { exact: true })).toBeVisible();
  expect((await new AxeBuilder({ page }).include(".lore-import-modal").withTags(["wcag2a", "wcag2aa", "wcag21aa", "wcag22aa"]).analyze()).violations).toEqual([]);
});

test("imports BDS only after preview, links a profile, and isolates the library", async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 420, height: 900 });
  await page.goto("/tests/fixtures/sidepanel.html");
  await page.getByRole("button", { name: "Лор", exact: true }).click();
  await page.getByRole("button", { name: "Загрузить готовый лор", exact: true }).click();
  // The file chooser and the drag-and-drop path use the same preview and validation.
  const source = { "  Оригинал  ": { value: "  Текст\nс переносом.  ", importance: "called" }, "Правило": { value: "Сохранить", importance: "always" } };
  await page.getByLabel("Выбрать JSON", { exact: true }).setInputFiles({ name: "Тестовый мир.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify(source)) });
  await expect(page.getByText("2 записей · всегда: 1 · автоподбор: 1 · вручную: 0 · выключено: 0")).toBeVisible();
  await expect(page.getByRole("button", { name: "Подтвердить импорт", exact: true })).toBeEnabled();
  await page.locator(".rp-import-preview summary").first().click();
  expect(await page.locator(".rp-import-preview pre").first().textContent()).toBe(source["  Оригинал  "].value);
  await page.getByRole("button", { name: "Подтвердить импорт", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Тестовый мир", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Мир и профили", exact: true }).click();
  await page.getByRole("button", { name: "Добавить профиль", exact: true }).click();
  await page.getByRole("textbox", { name: "Название", exact: true }).fill("Мира");
  await page.getByRole("checkbox", { name: /Оригинал/ }).check();
  await page.getByRole("button", { name: "Сохранить", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Мира", exact: true })).toBeVisible();
  await expect(page.getByText("Связанная память: 1", { exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("worlds-profiles.png"), fullPage: true });
  const accessibility = await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa", "wcag22aa"]).analyze();
  expect(accessibility.violations).toEqual([]);
  await page.getByRole("button", { name: "Лор", exact: true }).click();
  await page.getByRole("button", { name: "Список записей", exact: true }).click();
  await expect(page.getByText("Оригинал", { exact: true })).toBeVisible();
  await expect(page.getByText("Клятва Миры", { exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Карта мира", exact: true }).click();
  await page.getByRole("button", { name: /^Библиотека мира:/ }).click();
  await page.getByRole("menuitemradio", { name: "Без мира", exact: true }).click();
  await expect(page.getByText("Клятва Миры", { exact: true })).toBeVisible();
  await expect(page.getByText("Оригинал", { exact: true })).toHaveCount(0);
});

test("creates editable worlds and starters without sending anything", async ({ page }) => {
  await page.goto("/tests/fixtures/sidepanel.html");
  await page.getByRole("button", { name: "Лор", exact: true }).click();
  await page.getByRole("button", { name: "Создать свой мир", exact: true }).click();
  await page.getByRole("textbox", { name: "Название", exact: true }).fill("Новый мир");
  await page.getByRole("button", { name: "Создать мир", exact: true }).click();
  await page.getByRole("button", { name: "Закрыть карту", exact: true }).click();
  await page.getByRole("button", { name: "Мир и профили", exact: true }).click();
  await page.locator('details:has(select[aria-label="Перенести книгу в этот мир"]) > summary').click();
  await page.getByRole("combobox", { name: "Перенести книгу в этот мир", exact: true }).selectOption({ label: "Лунный предел" });
  await expect(page.getByRole("checkbox", { name: "Лунный предел", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Создать заготовку", exact: true }).click();
  await page.getByRole("textbox", { name: "Название", exact: true }).fill("Первая встреча");
  await page.getByRole("textbox", { name: "Первая реплика", exact: true }).fill("Открываю дверь.");
  await page.getByRole("textbox", { name: "Исходное состояние сюжета", exact: true }).fill("Раннее утро.");
  await page.getByRole("button", { name: "Сохранить", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Первая встреча", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Подготовить в пустом чате", exact: true }).click();
  await expect(page.getByText("Откройте DeepSeek, чтобы изменить сцену чата.")).toBeVisible();
});

test("world tree edits entry relationships without changing lore", async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 420, height: 900 });
  await page.goto("/tests/fixtures/sidepanel.html");
  await page.getByRole("button", { name: "Лор", exact: true }).click();
  await page.getByRole("button", { name: "Загрузить готовый лор", exact: true }).click();
  await page.getByLabel("Выбрать JSON", { exact: true }).setInputFiles({ name: "Древо.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify({ "Башня": { value: "Исходный текст башни", importance: "always" }, "Дверь": { value: "Исходный текст двери", importance: "called" } })) });
  await expect(page.getByText("Распознана память BDS", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Подтвердить импорт", exact: true }).click();
  await page.getByRole("button", { name: "Список записей", exact: true }).click();
  const tower = page.locator(".memory-card").filter({ has: page.getByRole("heading", { name: "Башня", exact: true }) });
  await tower.getByRole("button", { name: "Изменить", exact: true }).click();
  const dialog = page.getByRole("dialog");
  const linksSummary = dialog.locator(".rp-entry-links summary").filter({ hasText: /^Связи с другими записями/ });
  // Let Firefox finish focus-induced scrolling inside the bottom sheet before
  // Playwright calculates the click point. Still one normal, unforced click.
  await linksSummary.focus(); await linksSummary.click();
  await expect(dialog.locator(".rp-entry-links").last()).toHaveAttribute("open", "");
  await dialog.getByRole("checkbox", { name: "Дверь", exact: true }).check();
  await dialog.getByRole("textbox", { name: "Описание связи: Дверь", exact: true }).fill("возможный выход");
  await dialog.getByRole("button", { name: "Сохранить", exact: true }).click();
  await tower.getByRole("button", { name: "Изменить", exact: true }).click();
  await linksSummary.focus(); await linksSummary.click();
  await expect(dialog.getByRole("checkbox", { name: "Дверь", exact: true })).toBeChecked();
  await expect(dialog.getByRole("textbox", { name: "Описание связи: Дверь", exact: true })).toHaveValue("возможный выход");
  await expect(dialog.locator("textarea").first()).toHaveValue("Исходный текст башни");
  await dialog.getByRole("button", { name: "Отмена", exact: true }).click();
  await page.getByRole("button", { name: "Новая запись", exact: true }).click();
  await dialog.locator("input.input").first().fill("Новое событие");
  await dialog.locator("textarea").first().fill("Поздний дождь.");
  await dialog.getByRole("button", { name: "Сохранить", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Новое событие", exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("world-tree.png"), fullPage: true });
  const accessibility = await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa", "wcag22aa"]).analyze();
  expect(accessibility.violations).toEqual([]);
});

test("same importer recognizes a DeepRole world and refuses unrelated JSON", async ({ page }) => {
  await page.goto("/tests/fixtures/sidepanel.html");
  await page.getByRole("button", { name: "Лор", exact: true }).click();
  await page.getByRole("button", { name: "Загрузить готовый лор", exact: true }).click();
  const input = page.getByLabel("Выбрать JSON", { exact: true });
  await input.setInputFiles({ name: "bad.json", mimeType: "application/json", buffer: Buffer.from('{"format":"deeprole-backup"}') });
  await expect(page.getByRole("alert")).toContainText("Ничего не импортировано");
  await expect(page.getByRole("button", { name: "Подтвердить импорт", exact: true })).toHaveCount(0);
  const world = { id: "world", name: "Из DeepRole", description: "", color: "#64b5f6", contextBudget: 2000, relevanceThreshold: 6, createdAt: 1, updatedAt: 1 };
  await input.setInputFiles({ name: "world.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify({ format: "deeprole-world", version: 1, records: [{ kind: "world", id: world.id, data: world }] })) });
  await expect(page.getByText("Распознан мир DeepRole", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Подтвердить импорт", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Из DeepRole", exact: true })).toBeVisible();
});

test("RPG map supports window/full-screen, pan, zoom, search and node editing", async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1200, height: 850 });
  await page.goto("/tests/fixtures/sidepanel.html");
  await page.getByRole("button", { name: "Лор", exact: true }).click();
  await page.getByRole("button", { name: "Загрузить готовый лор", exact: true }).click();
  const world = { id: "w", name: "Лунная экспедиция", description: "Только тестовый мир", color: "#64b5f6", contextBudget: 2000, relevanceThreshold: 6, createdAt: 1, updatedAt: 1 };
  const entry = (id: string, title: string, content: string) => ({ id, title, content, entityIds: id === "tower" ? ["character"] : [], worldId: "w", bookId: null, keywords: [], activation: "smart", priority: "normal", enabled: true, source: { type: "manual" }, createdAt: 1, updatedAt: 1 });
  const entries = [ { ...entry("tower", "Северная башня", "Наблюдательная башня у озера."), links: [{ targetId: "door", label: "возможный проход", mode: "context" }] }, entry("door", "Закрытая дверь", "Старинная дверь с печатью."), entry("moon", "Лунный камень", "Светится ночью."), entry("oath", "Клятва", "Сохранить тайну."), entry("lake", "Озеро", "Холодное озеро."), entry("bridge", "Мост", "Соединяет берега.") ];
  const entity = { id: "character", worldId: "w", kind: "character", name: "Проводник", description: "Тестовый персонаж", aliases: [], memberIds: [], createdAt: 1, updatedAt: 1 };
  await page.getByLabel("Выбрать JSON", { exact: true }).setInputFiles({ name: "map.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify({ format: "deeprole-world", version: 1, records: [{ kind: "world", id: "w", data: world }, { kind: "entity", id: entity.id, data: entity }, ...entries.map((data) => ({ kind: "entry", id: data.id, data }))] })) });
  await page.getByRole("button", { name: "Подтвердить импорт", exact: true }).click();
  await page.getByRole("button", { name: "Открыть карту мира", exact: true }).click();
  const map = page.getByRole("dialog", { name: "Карта мира", exact: true });
  await map.getByRole("button", { name: "Развернуть на весь экран", exact: true }).click();
  await expect(map).toHaveClass(/is-full/);
  await expect(map.locator(".lm-node.node-entry")).toHaveCount(6);
  await expect(map.locator(".lm-node.node-world")).toHaveCount(1);
  await expect(map.locator(".edge-context")).toHaveCount(0);
  const before = await map.locator(".lm-space").getAttribute("style");
  const bounds = (await map.locator(".lm-viewport").boundingBox())!;
  await page.mouse.move(bounds.x + 12, bounds.y + 12); await page.mouse.down({ button: "middle" }); await page.mouse.move(bounds.x + 82, bounds.y + 52); await page.mouse.up({ button: "middle" });
  expect(await map.locator(".lm-space").getAttribute("style")).not.toBe(before);
  const zoomBefore = parseInt((await map.locator("output").textContent())!);
  await map.getByRole("button", { name: "Приблизить", exact: true }).click();
  expect(parseInt((await map.locator("output").textContent())!)).toBeGreaterThan(zoomBefore);
  await map.getByRole("button", { name: "Свернуть в окно", exact: true }).click();
  await expect(map).toHaveClass(/is-compact/);
  await map.getByRole("button", { name: "Развернуть на весь экран", exact: true }).click();
  await expect(map).toHaveClass(/is-full/);
  await map.getByRole("textbox", { name: "Найти запись или ветвь…", exact: true }).fill("Северная");
  await map.locator(".lm-results").getByRole("button", { name: "Северная башня", exact: true }).click();
  await expect(map.locator(".lm-details h3")).toHaveText("Северная башня");
  await expect(map.locator(".lm-details")).toContainText("возможный проход");
  await expect(map.locator(".edge-context")).toHaveClass(/is-highlighted/);
  await page.screenshot({ path: testInfo.outputPath("rpg-lore-map.png") });
  const accessibility = await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa", "wcag22aa"]).analyze();
  expect(accessibility.violations).toEqual([]);
  await map.getByText("Дополнительные действия", { exact: true }).click();
  await map.getByRole("button", { name: "Все настройки записи", exact: true }).click();
  await expect(map).toHaveCount(0);
  await expect(page.getByRole("dialog").locator("textarea").first()).toHaveValue("Наблюдательная башня у озера.");
  await page.getByRole("button", { name: "Отмена", exact: true }).click();
  await page.getByRole("button", { name: "Открыть карту мира", exact: true }).click();
  await page.keyboard.press("Escape");
  await expect(map).toHaveCount(0);
});
