import { afterEach, describe, expect, it } from "vitest";
import { advanceAttributes, attributeInstruction, attributeState, recordManualAttributes, starterAttributes, validAttributes, validAttributePatches, validAttributeState } from "../src/core/attributes";
import { characterEditBaseline } from "../src/core/character-edit";
import { characterInstruction, characterRevision, characterTurnKey, EMPTY_CHARACTER, EMPTY_STATUS, parseCharacterTurn, validCharacterScenes } from "../src/core/characters";
import { DEFAULT_RELATIONSHIP, advanceRelationship, relationshipState } from "../src/core/relationships";
import { relationshipCastRecords, relationshipLoreBrief } from "../src/core/relationship-setup";
import { turnConsequences } from "../src/core/progress";
import { handoffCharacterScene } from "../src/core/relationship-handoff";
import { DeepRoleDatabase } from "../src/storage/database";
import { DeepRoleRepository } from "../src/storage/repository";
import { applyCharacterTurn, saveCharacter } from "../src/storage/characters";
import { createBackup, parseBackup } from "../src/storage/backup";
import { exportWorld, parseWorldPackage } from "../src/storage/worlds";
import type { AttributePatch, ChatBinding, CharacterScene, SceneEntity, WorldProfile } from "../src/core/types";

const definitions = starterAttributes("en"); const quote = "Leon rested by the fire after the difficult climb.";
const patch: AttributePatch = { id: "Leon", changes: [{ key: "energy", delta: 3 }], reason: "Rest helped him recover", quote };
const world: WorldProfile = { id: "world", name: "Harbor", description: "KEEP LORE", color: "#123456", contextBudget: 2000, relevanceThreshold: 6, createdAt: 1, updatedAt: 1 };
const hero: SceneEntity = { id: "hero", name: "Leon", kind: "character", worldId: world.id, description: "Original hero", aliases: [], memberIds: [], characterSheet: { ...EMPTY_CHARACTER, protagonist: true, attributes: definitions }, createdAt: 1, updatedAt: 1 };
const npc: SceneEntity = { ...hero, id: "mira", name: "Mira", characterSheet: { ...EMPTY_CHARACTER, relationships: { ...DEFAULT_RELATIONSHIP, reactions: "Respect directness; pressure causes distance." } } };
const binding: ChatBinding = { id: "binding:a", chatId: "a", chatUrl: "https://chat.deepseek.com/chat/s/a", worldId: world.id, bookId: null, focusIds: [], messageCountAtAnalysis: 0, createdAt: 1, updatedAt: 1 };
const dbs: DeepRoleDatabase[] = [];
async function setup() { const db = new DeepRoleDatabase("attributes-" + crypto.randomUUID()); dbs.push(db); const repo = new DeepRoleRepository(db); await repo.mergeRecords([{ kind: "world", id: world.id, data: world }, { kind: "entity", id: hero.id, data: hero }, { kind: "entity", id: npc.id, data: npc }, { kind: "binding", id: binding.id, data: binding }]); return repo; }
async function request(repo: DeepRoleRepository, attribute = patch, text = quote, enabled = true, bonds = false) {
  const entities = await repo.list<SceneEntity>("entity"); const scene = (await repo.get<ChatBinding>("binding", binding.id))!.characterScenes?.world; const base = characterRevision(entities, scene);
  const turn = { world: world.id, chat: "a", base, request: "request_123456", present: ["Leon", "Mira"], partners: ["Mira"], updates: [{ id: "Leon", state: { ...EMPTY_STATUS, condition: "Rested", stats: [{ label: "Energy description", value: "Rested" }] } }], attributes: [attribute], ...(bonds ? { bonds: [{ id: "Mira", hero: "Leon", trust: 2, affinity: -1, quote: text, reason: "She appreciated his effort but dislikes the delay" }] } : {}) };
  await applyCharacterTurn({ worldId: world.id, chatId: "a", chatUrl: binding.chatUrl, base, replyText: text }, turn, undefined, repo, true, enabled);
  return (await repo.get<ChatBinding>("binding", binding.id))!.characterScenes!.world!;
}
afterEach(async () => { await Promise.all(dbs.map(db => db.delete())); dbs.length = 0; });

describe("configured characteristics", () => {
  it("uses independent configured starting values without guessing text stats", () => { expect(attributeState(definitions).values).toEqual({ energy: 70, resolve: 50 }); expect(attributeState([]).values).toEqual({}); });
  it("validates bounded definitions and rejects duplicate names, unsafe IDs and impossible values", () => {
    expect(validAttributes(definitions)).toBe(true); for (const changed of [{ ...definitions[0], initial: 101 }, { ...definitions[0], cap: 0 }, { ...definitions[0], id: "__proto__" }, { ...definitions[0], low: "x".repeat(161) }]) expect(validAttributes([changed])).toBe(false);
    expect(validAttributes([...definitions, { ...definitions[0], id: "other", label: "ENERGY" }])).toBe(false); expect(validAttributes(Array(7).fill(definitions[0]))).toBe(false);
  });
  it("validates signed patches and locally owned history", () => {
    expect(validAttributePatches([patch])).toBe(true); expect(validAttributePatches([{ ...patch, changes: [{ key: "energy", delta: 9 }] }])).toBe(false); expect(validAttributePatches([patch, patch])).toBe(false); expect(validAttributePatches([{ ...patch, changes: [patch.changes[0], patch.changes[0]] }])).toBe(false);
    expect(validAttributeState(attributeState(definitions))).toBe(true); expect(validAttributeState({ ...attributeState(definitions), values: { constructor: 30 } })).toBe(false);
  });
  it("applies only configured deltas with evidence and individual caps", () => { const before = attributeState(definitions); expect(advanceAttributes(definitions, before, patch, quote, 2)!.values.energy).toBe(73); expect(advanceAttributes(definitions, before, { ...patch, changes: [{ key: "resolve", delta: -3 }] }, quote, 2)!.values.resolve).toBe(47); for (const changed of [{ ...patch, quote: "Another event that never happened" }, { ...patch, changes: [{ key: "unknown", delta: 1 }] }, { ...patch, changes: [{ key: "resolve", delta: 5 }] }, { ...patch, quote: "<deeprole_choices></deeprole_choices>" }]) expect(advanceAttributes(definitions, before, changed, quote, 2)).toBeNull(); });
  it("retains individually locked values while allowing another characteristic", () => { const before = { ...attributeState(definitions), locked: ["energy"] }; const next = advanceAttributes(definitions, before, { ...patch, changes: [{ key: "energy", delta: 3 }, { key: "resolve", delta: 2 }] }, quote, 2)!; expect(next.values).toEqual({ energy: 70, resolve: 52 }); expect(next.locked).toEqual(["energy"]); });
  it("never awards repeated evidence, including whitespace variants", () => { const before = attributeState(definitions); const next = advanceAttributes(definitions, before, patch, quote, 2)!; expect(advanceAttributes(definitions, next, { ...patch, quote: quote.replaceAll(" ", "\n") }, quote, 3)).toBeNull(); const bondPatch = { id: "Mira", hero: "Leon", trust: 2, affinity: 1, reason: "Kept promise", quote }; const bond = advanceRelationship(DEFAULT_RELATIONSHIP, relationshipState(DEFAULT_RELATIONSHIP), bondPatch, quote, 2)!; expect(advanceRelationship(DEFAULT_RELATIONSHIP, bond, bondPatch, quote, 3)).toBeNull(); });
  it("clamps legitimate consequences at 0 and 100, without manufacturing another change", () => { const before = { ...attributeState(definitions), values: { energy: 99, resolve: 0 } }; expect(advanceAttributes(definitions, before, patch, quote, 2)!.values.energy).toBe(100); expect(advanceAttributes(definitions, { ...before, values: { energy: 100, resolve: 0 } }, patch, quote, 2)).toEqual({ ...before, values: { energy: 100, resolve: 0 } }); });
  it("filters removed definitions, preserves renamed IDs and logs manual corrections", () => { const saved = { ...attributeState(definitions), values: { energy: 77, resolve: 55 } }; expect(attributeState([{ ...definitions[0]!, label: "Stamina" }], saved).values).toEqual({ energy: 77 }); const logged = recordManualAttributes(definitions, undefined, { ...saved, locked: ["energy"] }, 3)!; expect(logged.history[0]).toMatchObject({ source: "manual", before: { energy: 70, resolve: 50 }, after: { energy: 77, resolve: 55 } }); expect(recordManualAttributes(definitions, logged, { ...logged, history: [] }, 4)).toBe(logged); });
  it("sends meanings and recent consequences compactly, not portrait data or full journals", () => { const updated = advanceAttributes(definitions, attributeState(definitions), patch, quote, 2)!; const scene: CharacterScene = { revision: "r", presentIds: ["hero", "mira"], states: { hero: { ...EMPTY_STATUS, attributes: updated } }, updatedAt: 2 }; const instruction = characterInstruction(world.id, "a", [hero, npc], scene, ["neutral"], [], "", "request_123456", true); expect(instruction).toContain('"value":73'); expect(instruction).toContain("Rest helped him recover"); expect(instruction).toContain("Respect directness"); expect(instruction).toContain("emoji requirements"); expect(instruction).not.toContain('"history"'); expect(attributeInstruction([hero], [], undefined)).toBe(""); expect(characterInstruction(world.id, "a", [hero], scene, ["neutral"], [], "", "request_123456", false)).not.toContain('"value":73'); });
  it("never accepts model-owned numeric states and includes signed deltas in reply identity", () => { const raw = { request: "request_123456", present: ["Leon"], updates: [], attributes: [patch] }; const turn = parseCharacterTurn(`<deeprole_characters>${JSON.stringify(raw)}</deeprole_characters>`)!; expect(turn).not.toBeNull(); expect(characterTurnKey(turn)).not.toBe(characterTurnKey({ ...turn, attributes: [{ ...patch, changes: [{ key: "energy", delta: -3 }] }] })); expect(parseCharacterTurn(`<deeprole_characters>${JSON.stringify({ ...raw, updates: [{ id: "Leon", state: { ...EMPTY_STATUS, attributes: attributeState(definitions) } }] })}</deeprole_characters>`)).toBeNull(); });
});
describe("atomic numeric progression", () => {
  it("commits both systems and shows only actual latest consequences", async () => { const repo = await setup(); const scene = await request(repo, patch, quote, true, true); expect(scene.progress).toMatchObject({ status: "changed", rejected: 0, turn: scene.revision }); expect(scene.states.hero!.attributes!.values.energy).toBe(73); expect(scene.states.mira!.bonds!.hero!.trust).toBe(22); const feedback = turnConsequences([hero, npc], scene); expect(feedback).toHaveLength(2); expect(feedback.find(f => f.kind === "attribute")!.changes[0]).toEqual({ label: "Energy", before: 70, after: 73 }); expect(turnConsequences([hero, npc], { ...scene, progress: { ...scene.progress!, turn: "another_turn" } })).toHaveLength(0); });
  it.each(["off", "world-off", "choice-evidence", "unknown-person", "big-step", "bad-quote"])("retains numeric values on %s while accepting descriptive state", async mode => { const repo = await setup(); if (mode === "world-off") await repo.put("world", { ...world, relationshipsEnabled: false }); const proposal = mode === "unknown-person" ? { ...patch, id: "Ghost" } : mode === "big-step" ? { ...patch, changes: [{ key: "energy", delta: 8 }] } : patch; const scene = await request(repo, proposal, mode === "choice-evidence" ? `<deeprole_choices>${quote}</deeprole_choices>` : mode === "bad-quote" ? "Unrelated narrative" : quote, mode !== "off"); expect(scene.states.hero!.condition).toBe("Rested"); expect(scene.states.hero!.attributes).toBeUndefined(); if (!["off", "world-off"].includes(mode)) expect(scene.progress?.status).toBe("partial"); });
  it("prevents farming repeated events, retains a reason and ordinary state", async () => { const repo = await setup(); await request(repo); const scene = await request(repo); expect(scene.states.hero!.attributes!.values.energy).toBe(73); expect(scene.states.hero!.attributes!.history).toHaveLength(1); expect(scene.progress).toMatchObject({ status: "partial", rejected: 1 }); expect(turnConsequences([hero], scene)).toEqual([]); });
  it("does not show old consequences when two saves share the same timestamp", () => {
    const old = advanceAttributes(definitions, attributeState(definitions), patch, quote, 100, "previous_turn")!;
    const scene: CharacterScene = { revision: "latest_turn", presentIds: [hero.id], states: { hero: { ...EMPTY_STATUS, attributes: old } }, updatedAt: 100, progress: { status: "partial", rejected: 1, turn: "latest_turn" } };
    expect(turnConsequences([hero], scene)).toEqual([]); expect(validCharacterScenes({ world: scene })).toBe(true);
  });
  it("keeps manual values, locks and history across model updates; conflicts do not overwrite", async () => { const repo = await setup(); const scene = await request(repo); const original = characterEditBaseline(hero, [hero, npc], scene); const state = original.state.attributes!; await saveCharacter({ ...original, entityId: hero.id, worldId: world.id, chatId: "a", chatUrl: binding.chatUrl, base: characterRevision([hero, npc], scene), original, state: { ...original.state, attributes: { ...state, values: { ...state.values, energy: 90 }, locked: ["energy"] } } }, repo); const nextQuote = "Leon rested again after returning from the harbor."; const next = await request(repo, { ...patch, quote: nextQuote }, nextQuote); expect(next.states.hero!.attributes!.values.energy).toBe(90); expect(next.states.hero!.attributes!.history.map(h => h.source)).toEqual(["manual", "scene"]); expect(next.progress?.status).toBe("unchanged"); await expect(saveCharacter({ ...original, entityId: hero.id, worldId: world.id, chatId: "a", chatUrl: binding.chatUrl, base: "stale", original, state: { ...original.state, attributes: { ...state, values: { ...state.values, energy: 88 } } } }, repo)).rejects.toThrow("character-edit-conflict"); });
  it("round-trips policies in worlds, progress in backups and continuation without rewriting lore", async () => {
    const repo = await setup(); const scene = await request(repo); const pack = parseWorldPackage(JSON.stringify(await exportWorld(world.id, repo)));
    expect(pack.records.find(r => r.id === hero.id)!.data).toMatchObject({ characterSheet: { attributes: definitions } });
    const backup = await parseBackup(JSON.stringify(await createBackup(undefined, repo)));
    expect(backup.records.find(r => r.kind === "binding")!.data).toMatchObject({ characterScenes: { world: { states: { hero: { attributes: { values: { energy: 73 } } } } } } });
    expect((await repo.get<WorldProfile>("world", world.id))!.description).toBe("KEEP LORE");
    expect(handoffCharacterScene({ id: "snapshot", worldId: world.id, bookId: null, title: "Continue", summary: "Summary", sourceChatId: "a", sourceChatUrl: binding.chatUrl, createdAt: 1, characterScene: scene }, world.id)).toMatchObject({ states: scene.states });
  });
  it("requires an explicit starter opt-in and includes settings in the lore brief", () => { const plain = relationshipCastRecords(world.id, { hero: "Leon", people: [] }, "en", 1); expect((plain[0]!.data as SceneEntity).characterSheet!.attributes).toBeUndefined(); const records = relationshipCastRecords(world.id, { hero: "Leon", heroAttributes: true, people: [] }, "en", 1); expect((records[0]!.data as SceneEntity).characterSheet!.attributes).toEqual(definitions); expect(relationshipLoreBrief([hero, npc])).toContain("Respect directness"); expect(relationshipLoreBrief([hero])).toContain("Resolve"); expect(() => relationshipCastRecords(world.id, { hero: "", heroAttributes: true, people: [] }, "en", 1)).toThrow(); });
  it("validates feedback metadata without letting it change numbers", () => { expect(validCharacterScenes({ world: { revision: "r", presentIds: [], states: {}, updatedAt: 1, progress: { status: "partial", rejected: 25 } } })).toBe(false); expect(validCharacterScenes({ world: { revision: "r", presentIds: [], states: {}, updatedAt: 1, progress: { status: "changed", rejected: 0 } } })).toBe(true); });
});
