import { afterEach, describe, expect, it } from "vitest";
import { castSources, castParts, castPrompt, parseCastDraft } from "../src/core/cast-initialization";
import { createCastJob, mutateCastJob, acceptCastReply, applyCastDraft } from "../src/storage/cast-initialization";
import { DeepRoleDatabase } from "../src/storage/database";
import { DeepRoleRepository } from "../src/storage/repository";
import { createBackup } from "../src/storage/backup";
import { exportWorld, parseWorldPackage, removeWorld } from "../src/storage/worlds";
import { EMPTY_CHARACTER, EMPTY_STATUS, validCharacterSheet, characterInstruction } from "../src/core/characters";
import { relationshipState, relationshipStage } from "../src/core/relationships";
import { castBinding, castDraft, castRecords } from "./fixtures/cast-data";
import type { ChatBinding, SceneEntity } from "../src/core/types";
const dbs: DeepRoleDatabase[] = [];
async function setup() { const db=new DeepRoleDatabase("cast-"+crypto.randomUUID());dbs.push(db);const repo=new DeepRoleRepository(db);await repo.mergeRecords(castRecords());return repo; }
afterEach(async()=>{await Promise.all(dbs.map(db=>db.delete()));dbs.length=0;});
async function ready(repo:DeepRoleRepository) {const job=await createCastJob("w","en",false,repo);await mutateCastJob(job.id,j=>({...j,phase:"ready",draft:castDraft(j.id),cleanup:"done"}),repo);return job;}
describe("cast sources and protocol",()=>{
 it("includes world lore, strips pictures and ignores other worlds",()=>{
  const records=castRecords();records.push({kind:"entity",id:"mira",data:{id:"mira",worldId:"w",kind:"character",name:"Mira",description:"Original lore",aliases:[],memberIds:[],characterSheet:{...EMPTY_CHARACTER,sprites:{neutral:"data:image/png;base64,PRIVATE"}},createdAt:2,updatedAt:2}},{kind:"entity",id:"other",data:{id:"other",worldId:"other",kind:"character",name:"Other",description:"SECRET",aliases:[],memberIds:[],createdAt:2,updatedAt:2}});
  const source=JSON.stringify(castSources(records,"w"));expect(source).toContain("Original lore");expect(source).not.toContain("PRIVATE");expect(source).not.toContain("SECRET");
 });
 it("splits complete input without losing a surrogate pair",()=>{const sources=[{id:"x",title:"X",text:"A".repeat(19950)+"😀".repeat(30000),at:1}];const parts=castParts(sources);expect(parts.join("")).toBe(JSON.stringify(sources));expect(parts.every(p=>p.length<=20000&&!/[\uD800-\uDBFF]$/u.test(p))).toBe(true);});
 it("rejects empty/oversized sources",()=>{expect(()=>castParts([])).toThrow("lore-empty");expect(()=>castParts([{id:"x",title:"X",text:"A".repeat(220000),at:1}])).toThrow("world-too-large");});
 it("validates request, exact evidence and local ranges",()=>{const sources=castSources(castRecords(),"w"),draft=castDraft("request");expect(parseCastDraft(JSON.stringify(draft),"request",sources).characters).toHaveLength(2);
  expect(()=>parseCastDraft(JSON.stringify(draft),"other",sources)).toThrow();draft.characters[1]!.sheet.relationships!.initial.trust=101;expect(()=>parseCastDraft(JSON.stringify(draft),"request",sources)).toThrow();draft.characters[1]!.sheet.relationships!.initial.trust=82;draft.characters[1]!.evidence[0]!.quote="Invented event";expect(()=>parseCastDraft(JSON.stringify(draft),"request",sources)).toThrow("invalid-evidence");
 });
 it("rejects duplicate people, invalid milestones and protagonist partners",()=>{const sources=castSources(castRecords(),"w");for(const change of [(d:ReturnType<typeof castDraft>)=>d.characters[1]!.name="Leon",(d:ReturnType<typeof castDraft>)=>d.characters[1]!.completed=["future"],(d:ReturnType<typeof castDraft>)=>d.partners=["p1"]]){const d=castDraft("x");change(d);expect(()=>parseCastDraft(JSON.stringify(d),"x",sources)).toThrow();}});
 it("never accepts remote images or numeric patches in generated state",()=>{const d:any=castDraft("x");d.characters[0].sheet.sprites={neutral:"https://evil.test/img"};d.characters[0].state.bonds={evil:{trust:100}};const parsed=parseCastDraft(JSON.stringify(d),"x",castSources(castRecords(),"w"));expect(parsed.characters[0]!.sheet.sprites).toEqual({});expect(parsed.characters[0]!.state.bonds).toBeUndefined();});
});
describe("atomic preparation",()=>{
 it("reuses a running job and consumes the automatic flag",async()=>{const repo=await setup();const a=await createCastJob("w","en",false,repo),b=await createCastJob("w","en",true,repo);expect(b.id).toBe(a.id);expect((await repo.get<any>("world","w")).autoPrepareCharacters).toBe(false);});
 it("waits for exact pending step and gives malformed output one repair",async()=>{const repo=await setup(),job=await createCastJob("w","en",false,repo);await expect(acceptCastReply(job.id,0,"received",repo)).rejects.toThrow("stale-step");await mutateCastJob(job.id,j=>({...j,phase:"reading",awaiting:true}),repo);await acceptCastReply(job.id,0,"received",repo);await mutateCastJob(job.id,j=>({...j,phase:"analyzing",awaiting:true}),repo);const repair=await acceptCastReply(job.id,1,"bad",repo);expect(repair.repair).toBe(true);expect(castPrompt(repair)).toContain("-repair]");await mutateCastJob(job.id,j=>({...j,awaiting:true}),repo);expect((await acceptCastReply(job.id,1,"bad again",repo)).phase).toBe("error");});
 it("blocks a second service until its previous chat is cleaned",async()=>{const repo=await setup(),j=await ready(repo);await mutateCastJob(j.id,v=>({...v,cleanup:"failed"}),repo);await expect(createCastJob("w","en",true,repo)).rejects.toThrow("cleanup-required");});
 it("installs all profiles, protagonist, characteristics, relationships and completed events",async()=>{const repo=await setup(),j=await ready(repo);expect(await applyCastDraft(j.id,castDraft(j.id),["p1","p2"],"p1",repo)).toBe(2);const people=await repo.list<SceneEntity>("entity"),hero=people.find(e=>e.name==="Leon")!,mira=people.find(e=>e.name==="Mira")!;expect(hero.characterSheet!.protagonist).toBe(true);expect(mira.characterSheet!.background).toBe("Traveller");expect(validCharacterSheet(mira.characterSheet)).toBe(true);const scene=(await repo.get<ChatBinding>("binding",castBinding.id))!.characterScenes!.w!;expect(scene.states[mira.id]!.attributes!.values.energy).toBe(75);expect(scene.states[mira.id]!.bonds![hero.id]!.trust).toBe(82);expect(scene.states[mira.id]!.bonds![hero.id]!.completed).toEqual(["promise"]);expect(relationshipStage(relationshipState(mira.characterSheet!.relationships!))).toBe("close");expect(scene.partnerIds).toEqual([mira.id]);expect(characterInstruction("w","a",people,undefined,["neutral"],[], "Mira")).toContain("Rested");expect((await repo.get<any>("world","w")).description).toBe((castRecords()[0]!.data as import("../src/core/types").WorldProfile).description);});
 it("preserves manual profiles, images, played numbers, locks and history",async()=>{const repo=await setup();const old:SceneEntity={id:"mira",worldId:"w",kind:"character",name:"Mira",description:"KEEP",aliases:[],memberIds:[],characterSheet:{...EMPTY_CHARACTER,appearance:"Manual coat",sprites:{neutral:"data:image/png;base64,AAAA"}},createdAt:1,updatedAt:1};const state={...EMPTY_STATUS,condition:"Played",attributes:{values:{energy:23},locked:["energy"],history:[]}};await repo.put("entity",old);await repo.put("binding",{...castBinding,characterScenes:{w:{revision:"old",presentIds:["mira"],states:{mira:state},updatedAt:1}}});const j=await ready(repo);await applyCastDraft(j.id,castDraft(j.id),["p1","p2"],"p1",repo);const entity=(await repo.get<SceneEntity>("entity","mira"))!;expect(entity.description).toBe("KEEP");expect(entity.characterSheet!.appearance).toBe("Manual coat");expect(entity.characterSheet!.sprites).toEqual(old.characterSheet!.sprites);expect(entity.characterSheet!.background).toBe("Traveller");expect((await repo.get<ChatBinding>("binding",castBinding.id))!.characterScenes!.w!.states.mira).toEqual(state);});
 it("rejects changed lore, missing hero and remapping atomically",async()=>{const repo=await setup(),j=await ready(repo);await expect(applyCastDraft(j.id,castDraft(j.id),["p2"],"p1",repo)).rejects.toThrow("hero-required");const d=castDraft(j.id);d.characters[0]!.name="Another";await expect(applyCastDraft(j.id,d,["p1","p2"],"p1",repo)).rejects.toThrow("invalid-result");await repo.put("world",{...castRecords()[0]!.data as any,description:"New lore"});await expect(applyCastDraft(j.id,castDraft(j.id),["p1","p2"],"p1",repo)).rejects.toThrow("lore-changed");expect(await repo.list("entity")).toHaveLength(0);});
 it("removes preparation sources when its world is deleted",async()=>{const repo=await setup();await ready(repo);await removeWorld("w",repo);expect(await repo.list("cast")).toHaveLength(0);});
 it("excludes service lore/drafts from world exports and backups",async()=>{const repo=await setup();await ready(repo);const backup=await createBackup(undefined,repo) as import("../src/core/types").BackupPayload;expect(backup.records.some(r=>r.kind==="cast")).toBe(false);expect((await exportWorld("w",repo)).records.some(r=>r.kind==="cast")).toBe(false);expect(parseWorldPackage(JSON.stringify(await exportWorld("w",repo)))).not.toBeNull();});
});
