import { afterEach, describe, expect, it, vi } from "vitest";
import { Blob as NodeBlob } from "node:buffer";
import { ImageTransport, requestBody, ImageApiError } from "../src/adapters/image/transport";
import { OpenAiImagesProvider } from "../src/adapters/image/openai-images";
import { VeniceNativeProvider } from "../src/adapters/image/venice-native";
import { dataImageBlob, normalizeImage } from "../src/adapters/image/image-codec";
import { ImageJobs } from "../src/storage/image-jobs";
import { saveImageSettings } from "../src/storage/image-settings";
import { saveProviderKey } from "../src/storage/image-keys";
import { DEFAULT_IMAGE_SETTINGS } from "../src/core/image-generation";
import { DeepRoleDatabase } from "../src/storage/database";
import { DeepRoleRepository } from "../src/storage/repository";
import { imageSenderAllowed } from "../src/adapters/image/background-handler";
import { imageDeltaInstruction } from "../src/core/image-prompt";
import { profile, tinyImage, realPng, world, illustration } from "./image-fixtures";
const secret = "SYNTHETIC-KEY-EXAMPLE";
const permitted = async () => true;
const normalized = vi.fn(async () => tinyImage);
function json(value: unknown, headers = {}) { return new Response(JSON.stringify(value), { headers: { "content-type": "application/json", ...headers } }); }
afterEach(() => { vi.unstubAllGlobals(); vi.restoreAllMocks(); });
describe("documented image adapters (mock fetch only)", () => {
  it("preserves a model-specific seed literally and refuses a conflicting character seed before fetch", () => { const fetchMock = vi.fn(); vi.stubGlobal("fetch", fetchMock); const config = { ...profile, extraParams: { seed: -1, unknown: "unchanged" } }; expect(requestBody(config, { prompt: "Forest" }).seed).toBe(-1); expect(() => requestBody(config, { prompt: "Forest", seed: 7 })).toThrow("seedConflict"); expect(fetchMock).not.toHaveBeenCalled(); });
  it.each(["openai", "venice"])("passes extraParams unchanged in the %s request", async kind => {
    const extraParams = { future_model_option: { xs: [null, true, "  literal  ", 2.75] }, output_format: "png", vendor_array: [1, 2, 3] };
    const config = { ...profile, extraParams }; const fetchMock = vi.fn(async () => json(kind === "openai" ? { data: [{ b64_json: realPng }] } : { images: [realPng] })); vi.stubGlobal("fetch", fetchMock);
    const transport = new ImageTransport(config, secret, permitted, normalized); const provider = kind === "openai" ? new OpenAiImagesProvider(config, transport) : new VeniceNativeProvider(config, transport);
    await provider.generate({ prompt: "Ordinary forest scene" }); const body = JSON.parse((fetchMock.mock.calls[0] as unknown as [string, RequestInit])[1].body as string);
    for (const [key, value] of Object.entries(extraParams)) expect(body[key]).toEqual(value); expect(body.prompt).toBe("Ordinary forest scene"); expect(fetchMock).toHaveBeenCalledTimes(1);
  });
  it("rejects service overrides without silently dropping them or calling fetch", async () => { const fetchMock = vi.fn(); vi.stubGlobal("fetch", fetchMock); expect(() => requestBody({ ...profile, extraParams: { prompt: "replace" } }, { prompt: "Keep" })).toThrow(); expect(fetchMock).not.toHaveBeenCalled(); });
  it("sends references as data URLs in official OpenAI JSON edit schema", async () => { const fetchMock = vi.fn(async () => json({ data: [{ b64_json: realPng }] })); vi.stubGlobal("fetch", fetchMock); await new OpenAiImagesProvider(profile, new ImageTransport(profile, secret, permitted, normalized)).edit({ prompt: "Forest", images: ["data:image/png;base64," + realPng] }); const call = fetchMock.mock.calls[0] as unknown as [string, RequestInit]; expect(call[0]).toMatch(/\/images\/edits$/); expect(JSON.parse(call[1].body as string).images).toEqual([{ image_url: "data:image/png;base64," + realPng }]); });
  it.each([1, 2])("parses Venice binary edit with %s references, not JSON", async count => { const config = { ...profile, kind: "venice-native" as const, editModelId: "synthetic-edit-model", maxReferences: 2 }; const fetchMock = vi.fn(async () => new Response(Uint8Array.from(atob(realPng), c => c.charCodeAt(0)), { headers: { "content-type": "image/png", "x-venice-is-blurred": "true", "x-venice-is-content-violation": "false", "x-venice-model-deprecation-warning": "Retiring" } })); vi.stubGlobal("fetch", fetchMock); const result = await new VeniceNativeProvider(config, new ImageTransport(config, secret, permitted, normalized)).edit({ prompt: "Ordinary scene", images: Array(count).fill("data:image/png;base64," + realPng) }); expect(result.image).toBe(tinyImage); expect(result.headers).toEqual({ "x-venice-is-blurred": "true", "x-venice-is-content-violation": "false", "x-venice-model-deprecation-warning": "Retiring" }); const body = JSON.parse((fetchMock.mock.calls[0] as unknown as [string, RequestInit])[1].body as string); expect(count === 1 ? body.image : body.images).toEqual(count === 1 ? realPng : Array(count).fill("data:image/png;base64," + realPng)); });
  it.each([[401, "unauthorized"], [402, "balance"], [403, "forbidden"], [415, "unsupported"], [429, "rate"], [500, "server"], [503, "unavailable"]])("maps %s without retries or leaking response body", async (status, code) => { const fetchMock = vi.fn(async () => new Response(secret, { status: status as number })); vi.stubGlobal("fetch", fetchMock); await expect(new OpenAiImagesProvider(profile, new ImageTransport(profile, secret, permitted, normalized)).generate({ prompt: "Ordinary scene" })).rejects.toMatchObject({ code }); expect(fetchMock).toHaveBeenCalledTimes(1); });
  it("never calls the network for a disabled profile or missing permission", async () => { const fetchMock = vi.fn(); vi.stubGlobal("fetch", fetchMock); const config = { ...profile, enabled: false }; await expect(new ImageTransport(config, secret, permitted).request("/models")).rejects.toMatchObject({ code: "disabled" }); await expect(new ImageTransport(profile, secret, async () => false).request("/models")).rejects.toMatchObject({ code: "permission" }); expect(fetchMock).not.toHaveBeenCalled(); });
  it("reads actual Venice metadata without an inventory or guessed price", async () => { const fetchMock = vi.fn(async (url: string) => json({ data: [{ id: url.includes("inpaint") ? "synthetic-edit" : "synthetic-new-model", model_spec: { name: "Synthetic model", privacy: "private", pricing: { usd: .123 }, constraints: { promptCharacterLimit: 850, aspectRatios: ["3:4"], steps: { min: 3, max: 9 } }, capabilities: { maxInputImages: 4 } } }] })); vi.stubGlobal("fetch", fetchMock); const models = await new VeniceNativeProvider(profile, new ImageTransport(profile, secret, permitted)).listModels(); expect(models).toHaveLength(2); expect(models[0]).toMatchObject({ priceUsd: .123, maxInputImages: 4, promptLimit: 850, constraints: { aspectRatios: ["3:4"] } }); expect(models[1]?.supportsEdit).toBe(true); expect(fetchMock).toHaveBeenCalledTimes(2); });
  it("keeps unavailable OpenAI model metadata undefined", async () => { vi.stubGlobal("fetch", vi.fn(async () => json({ data: [{ id: "synthetic-model" }] }))); const models = await new OpenAiImagesProvider(profile, new ImageTransport(profile, secret, permitted)).listModels(); expect(models).toEqual([{ id: "synthetic-model", label: "synthetic-model" }]); });
  it("downloads URL responses without leaking authorization to the image host", async () => { const fetchMock = vi.fn(async (url: string) => url.includes("generations") ? json({ data: [{ url: "https://cdn.example.test/result.png" }] }) : new Response(Uint8Array.from(atob(realPng), c => c.charCodeAt(0)), { headers: { "content-type": "image/png" } })); vi.stubGlobal("fetch", fetchMock); await new OpenAiImagesProvider(profile, new ImageTransport(profile, secret, permitted, normalized)).generate({ prompt: "Forest" }); const second = fetchMock.mock.calls[1] as unknown as [string, RequestInit]; expect(second[1].headers).toBeUndefined(); expect(second[1].credentials).toBe("omit"); expect(second[1].redirect).toBe("error"); });
  it("refuses an unapproved image domain without downloading it", async () => { const fetchMock = vi.fn(async () => json({ data: [{ url: "https://cdn.example.test/result.png" }] })); vi.stubGlobal("fetch", fetchMock); await expect(new OpenAiImagesProvider(profile, new ImageTransport(profile, secret, async url => url.startsWith(profile.baseUrl), normalized)).generate({ prompt: "Forest" })).rejects.toMatchObject({ code: "downloadOrigin" }); expect(fetchMock).toHaveBeenCalledTimes(1); });
  it("times out once, without retry", async () => { const fetchMock = vi.fn((_url: string, init: RequestInit) => new Promise<Response>((_resolve, reject) => init.signal!.addEventListener("abort", () => reject(new Error("aborted"))))); vi.stubGlobal("fetch", fetchMock); await expect(new ImageTransport(profile, secret, permitted, normalized, 10).request("/models")).rejects.toMatchObject({ code: "timeout" }); expect(fetchMock).toHaveBeenCalledTimes(1); });
  it.each([false, true])("normalizes JPEG with bounded dimensions (reference=%s)", async reference => { vi.stubGlobal("Blob", NodeBlob); const close = vi.fn(); vi.stubGlobal("createImageBitmap", vi.fn(async () => ({ width: 2000, height: 3000, close }))); const sizes: number[][] = []; vi.stubGlobal("OffscreenCanvas", class { constructor(public width: number, public height: number) { sizes.push([width, height]); } getContext() { return { fillRect: vi.fn(), drawImage: vi.fn() }; } async convertToBlob() { return new NodeBlob([Uint8Array.of(0xff, 0xd8, 0xff)], { type: "image/jpeg" }); } }); const result = await normalizeImage(dataImageBlob("data:image/png;base64," + realPng), reference); expect(result).toMatch(/^data:image\/jpeg;base64,/); expect(close).toHaveBeenCalledOnce(); const [w, h] = sizes[0]!; expect(reference ? w! * h! : Math.max(w!, h!)).toBeLessThanOrEqual(reference ? 1_500_000 : 768); });
  it("accepts only real image signatures and closes failed decoders", async () => { expect(() => dataImageBlob("data:image/jpeg;base64,YQ==")).toThrow(); vi.stubGlobal("createImageBitmap", vi.fn(async () => ({ width: 100_000, height: 100_000, close: vi.fn() }))); await expect(normalizeImage(new NodeBlob(["x"], { type: "image/png" }) as Blob)).rejects.toThrow(); });
  it("authorizes model access only from extension UI, never the page", () => { const ui = "chrome-extension://extension/"; expect(imageSenderAllowed({ id: "extension", url: ui + "sidepanel.html" }, "extension", ui, true)).toBe(true); expect(imageSenderAllowed({ id: "extension", url: "https://chat.deepseek.com/chat/s/a", tab: { id: 1 } }, "extension", ui, true)).toBe(false); expect(imageSenderAllowed({ id: "other", url: ui + "sidepanel.html" }, "extension", ui, true)).toBe(false); });
});
describe("background jobs and library boundaries", () => {
  it("persists only a scoped result, without keys, reference bytes or metadata in DeepSeek", async () => { const repo = new DeepRoleRepository(new DeepRoleDatabase("image-job-test-" + crypto.randomUUID())); await repo.put("world", world); await saveProviderKey(profile.id, secret); await saveImageSettings({ ...DEFAULT_IMAGE_SETTINGS, enabled: true, profiles: [profile] }); const generate = vi.fn(async () => ({ image: tinyImage, headers: { "x-venice-is-blurred": "false" } })); const createProvider = vi.fn(() => ({ generate, edit: vi.fn(), listModels: vi.fn() })); const jobs = new ImageJobs(repo, permitted, createProvider); const input = { worldId: world.id, chatId: "a", chatUrl: "https://chat.deepseek.com/chat/s/a", messageKey: illustration.messageKey, providerId: profile.id, prompt: "Forest at dusk", referenceKeys: [] }; const result = await jobs.run(input); expect(await repo.get("illustration", result.id)).toEqual(result); expect(JSON.stringify(await repo.rawRecords())).not.toContain(secret); expect(generate).toHaveBeenCalledOnce(); expect(imageDeltaInstruction("Copper hair", "Forest")).not.toContain(result.image); await expect(jobs.remove({ ...input, chatId: "other" }, result.id)).rejects.toBeInstanceOf(ImageApiError); await jobs.remove(input, result.id); expect(await repo.list("illustration")).toHaveLength(0); await repo.clear(); });
  it("disabled generation never creates a provider or changes lore", async () => { const createProvider = vi.fn(); const jobs = new ImageJobs(undefined, permitted, createProvider); await expect(jobs.run({ worldId: world.id, chatId: "a", chatUrl: "https://chat.deepseek.com/chat/s/a", messageKey: "reply", providerId: profile.id, prompt: "Forest", referenceKeys: [] })).rejects.toMatchObject({ code: "disabled" }); expect(createProvider).not.toHaveBeenCalled(); });
});
