import { describe, expect, it } from "vitest";
import { attributeBand, attributeInstruction, attributeMeaning, attributeState, starterAttributes, validAttributes } from "../src/core/attributes";
import { characterEditBaseline, mergeCharacterEdit } from "../src/core/character-edit";
import { characterInstruction, EMPTY_CHARACTER, EMPTY_STATUS, validCharacterSheet } from "../src/core/characters";
import { DEFAULT_RELATIONSHIP, relationshipGate, relationshipInstruction, relationshipRequirements, relationshipState, validRelationshipProfile } from "../src/core/relationships";
import { relationshipLoreBrief } from "../src/core/relationship-setup";
import type { CharacterScene, SceneEntity } from "../src/core/types";

const definitions = starterAttributes("en");
const hero: SceneEntity = { id: "hero", name: "Leon", kind: "character", worldId: "world", description: "KEEP HERO LORE", aliases: [], memberIds: [], characterSheet: { ...EMPTY_CHARACTER, protagonist: true, adultConfirmed: true, attributes: definitions }, createdAt: 1, updatedAt: 1 };
const npc: SceneEntity = { ...hero, id: "mira", name: "Mira", characterSheet: { ...EMPTY_CHARACTER, adultConfirmed: true, relationships: { ...structuredClone(DEFAULT_RELATIONSHIP), romance: true, stageBehavior: { guarded: "Keeps plans private", trusting: "Shares plans, dislikes pressure" }, milestones: [{ id: "promise", label: "Keep a promise" }, { id: "visit", label: "Visit the harbor", required: false }] } } };
const scene: CharacterScene = { revision: "r", presentIds: [hero.id, npc.id], states: { hero: { ...EMPTY_STATUS, attributes: attributeState(definitions) }, mira: { ...EMPTY_STATUS, bonds: { hero: { ...relationshipState(npc.characterSheet!.relationships!), trust: 60, affinity: 80 } } } }, updatedAt: 2 };

describe("stage behavior and independent achievements", () => {
  it("accepts optional stage descriptions without changing old profiles", () => { expect(validRelationshipProfile(DEFAULT_RELATIONSHIP)).toBe(true); expect(validCharacterSheet(npc.characterSheet)).toBe(true); expect(validRelationshipProfile({ ...DEFAULT_RELATIONSHIP, stageBehavior: { unknown: "invented" } })).toBe(false); expect(validRelationshipProfile({ ...DEFAULT_RELATIONSHIP, stageBehavior: { close: "x".repeat(241) } })).toBe(false); });
  it("rejects malformed required flags while preserving legacy requirements", () => { expect(validRelationshipProfile({ ...DEFAULT_RELATIONSHIP, milestones: [{ id: "event", label: "A promise", required: "false" }] })).toBe(false); const person = { ...npc, characterSheet: { ...npc.characterSheet!, relationships: { ...npc.characterSheet!.relationships!, milestones: [{ id: "event", label: "Promise" }] } } }; expect(relationshipGate(person, hero, { ...relationshipState(DEFAULT_RELATIONSHIP), trust: 100, affinity: 100 })).toBe("milestonesNeeded"); });
  it("optional achievements never block closeness but required events do", () => { const state = { ...relationshipState(DEFAULT_RELATIONSHIP), trust: 100, affinity: 100 }; expect(relationshipGate(npc, hero, state)).toBe("milestonesNeeded"); expect(relationshipGate(npc, hero, { ...state, completed: ["promise"] })).toBe("eligible"); expect(relationshipRequirements(npc, hero, state)!.events.map(e => e.id)).toEqual(["promise"]); });
  it("lists every unmet condition without hiding them behind the first one", () => { const state = relationshipState(DEFAULT_RELATIONSHIP); expect(relationshipRequirements(npc, { ...hero, characterSheet: { ...hero.characterSheet!, adultConfirmed: false } }, state)).toMatchObject({ adults: false, trust: 50, affinity: 45, events: [{ id: "promise" }] }); expect(relationshipRequirements({ ...npc, characterSheet: { ...npc.characterSheet!, relationships: { ...DEFAULT_RELATIONSHIP, romance: false } } }, hero, state)).toBeNull(); });
  it("supplies only current stage behavior, not hypothetical future rewards", () => { const prompt = relationshipInstruction([hero, npc], [npc], scene); expect(prompt).toContain('"behavior":"Shares plans, dislikes pressure"'); expect(prompt).not.toContain("Keeps plans private"); expect(prompt).toContain('"required":false'); });
  it("lore setup includes definitions but never marks planned events completed", () => { const prompt = relationshipLoreBrief([hero, npc]); expect(prompt).toContain("Keeps plans private"); expect(prompt).toContain('"required":false'); expect(prompt).not.toContain('"done":true'); expect(hero.description).toBe("KEEP HERO LORE"); });
});
describe("locally resolved characteristic states", () => {
  it.each([[0, "low"], [30, "low"], [31, "middle"], [69, "middle"], [70, "high"], [100, "high"]] as const)("resolves legacy value %s to %s", (value, band) => { expect(attributeBand(definitions[0]!, value)).toBe(band); });
  it("uses player boundaries and does not apply extremes in the middle", () => { const a = { ...definitions[0]!, lowAt: 20, highAt: 80 }; expect(attributeMeaning(a, 20)).toBe(a.low); expect(attributeMeaning(a, 21)).toBe(""); expect(attributeMeaning(a, 79)).toBe(""); expect(attributeMeaning(a, 80)).toBe(a.high); });
  it("rejects overlapping, fractional, out-of-range boundaries", () => { for (const patch of [{ lowAt: 70 }, { highAt: 30 }, { lowAt: 0.5 }, { lowAt: -1 }, { highAt: 101 }, { lowAt: 100, highAt: 100 }]) expect(validAttributes([{ ...definitions[0]!, ...patch }])).toBe(false); expect(validAttributes([{ ...definitions[0]!, lowAt: 0, highAt: 1 }])).toBe(true); });
  it("sends the same active meaning as the UI without inferring values", () => { const prompt = attributeInstruction([hero], [hero], scene); expect(prompt).toContain('"band":"high"'); expect(prompt).toContain('"meaning":"Rested; can sustain effort"'); expect(prompt).toContain('"band":"middle","meaning":""'); });
});
describe("read-only service context", () => {
  it("keeps current values and rules but requests no plot or numeric update", () => { const prompt = characterInstruction("world", "a", [hero, npc], scene, ["neutral"], [], "", "request_123456", true, true); expect(prompt).toContain("Read-only character reference"); expect(prompt).toContain('"trust":60'); expect(prompt).toContain('"value":70'); expect(prompt).toContain("emoji requirements"); expect(prompt).not.toContain("Schema:"); expect(prompt).not.toContain("Continue the story normally"); expect(prompt).not.toContain("append one"); expect(prompt).not.toContain("optionally add"); });
  it("disabled services expose no numeric tracking state", () => { const prompt = characterInstruction("world", "a", [hero, npc], scene, ["neutral"], [], "", "request_123456", false, true); expect(prompt).toContain("Numeric tracking is paused"); expect(prompt).not.toContain('"trust":60'); expect(prompt).not.toContain('"value":70'); });
});
describe("independent edits during an answer", () => {
  const baseline = () => characterEditBaseline(hero, [hero, npc], scene);
  it("merges a manual resolve edit with model energy, preserving the committed log", () => { const before = baseline(); const draft = structuredClone(before); draft.state.attributes!.values.resolve = 90; const live = structuredClone(before); live.state.attributes!.values.energy = 73; live.state.attributes!.history = [{ at: 3, source: "scene", before: before.state.attributes!.values, after: live.state.attributes!.values, reason: "Rest", quote: "Leon rested by the fire" }]; const merged = mergeCharacterEdit(before, draft, live); expect(merged.state.attributes!.values).toEqual({ energy: 73, resolve: 90 }); expect(merged.state.attributes!.history).toEqual(live.state.attributes!.history); });
  it("merges individual locks without erasing another scale's progress", () => { const before = baseline(); const draft = structuredClone(before); draft.state.attributes!.locked = ["resolve"]; const live = structuredClone(before); live.state.attributes!.values.energy = 73; live.state.attributes!.locked = ["energy"]; expect(mergeCharacterEdit(before, draft, live).state.attributes).toMatchObject({ values: { energy: 73 }, locked: ["energy", "resolve"] }); });
  it("rejects two different corrections to the same value", () => { const before = baseline(); const draft = structuredClone(before); draft.state.attributes!.values.energy = 90; const live = structuredClone(before); live.state.attributes!.values.energy = 73; expect(() => mergeCharacterEdit(before, draft, live)).toThrow("character-edit-conflict"); });
  it("normalizes initial state for a form opened before the first model update", () => { const empty = { ...scene, states: {} }; const before = characterEditBaseline(hero, [hero, npc], empty); const draft = structuredClone(before); draft.state.attributes = attributeState(definitions); draft.state.attributes.values.resolve = 90; const live = baseline(); live.state.attributes!.values.energy = 73; expect(mergeCharacterEdit(before, draft, live).state.attributes!.values).toEqual({ energy: 73, resolve: 90 }); });
  it("merges independent relationship axes and milestone completions", () => { const before = characterEditBaseline(npc, [hero, npc], scene); const draft = structuredClone(before); draft.state.bonds!.hero!.affinity = 90; draft.state.bonds!.hero!.completed = ["visit"]; const live = structuredClone(before); live.state.bonds!.hero!.trust = 63; live.state.bonds!.hero!.completed = ["promise"]; expect(mergeCharacterEdit(before, draft, live).state.bonds!.hero).toMatchObject({ trust: 63, affinity: 90, completed: ["visit", "promise"] }); });
  it("rejects overlapping axes instead of silently replacing the model result", () => { const before = characterEditBaseline(npc, [hero, npc], scene); const draft = structuredClone(before); draft.state.bonds!.hero!.trust = 90; const live = structuredClone(before); live.state.bonds!.hero!.trust = 63; expect(() => mergeCharacterEdit(before, draft, live)).toThrow("character-edit-conflict"); });
});
