import { Select } from "./Select";
import { Plus, Trash2 } from "lucide-react";
import { attributeBand, attributeMeaning, attributeState, starterAttributes } from "../../core/attributes";
import { immersionText } from "../../core/immersion-i18n";
import { createId } from "../../core/id";
import { progressText, type ProgressCopyKey } from "../../core/progress-i18n";
import { relationshipText } from "../../core/relationship-i18n";
import type { CharacterAttribute, CharacterSheet, CharacterStatus, Locale } from "../../core/types";
import { ScoreInput } from "./Relationships";

export function AttributeSummary({ locale, sheet, state }: { locale: Locale; sheet?: CharacterSheet; state?: CharacterStatus }) {
  if (!sheet?.attributes?.length) return null;
  const current = attributeState(sheet.attributes, state?.attributes);
  return <span className="dr-bond-summary dr-attribute-summary" aria-label={progressText(locale, "title")}>{sheet.attributes.slice(0, 3).map(a => <small key={a.id}>{a.label} {current.values[a.id]}{current.locked.includes(a.id) ? ` · ${progressText(locale, "lockedShort")}` : ""}</small>)}</span>;
}
export function AttributeEditor({ locale, sheet, state, profileOnly = false, enabled = true, disabled = false, onSheet, onState }: { locale: Locale; sheet: CharacterSheet; state: CharacterStatus; profileOnly?: boolean; enabled?: boolean; disabled?: boolean; onSheet: (sheet: CharacterSheet) => void; onState: (state: CharacterStatus) => void }) {
  const t = (key: ProgressCopyKey) => progressText(locale, key); const definitions = sheet.attributes ?? []; const current = attributeState(definitions, state.attributes);
  const duplicate = definitions.some((a, index) => !!a.label.trim() && definitions.some((other, otherIndex) => otherIndex !== index && other.label.trim().toLocaleLowerCase() === a.label.trim().toLocaleLowerCase()));
  const last = current.history[0];
  const update = (id: string, patch: Partial<CharacterAttribute>) => onSheet({ ...sheet, attributes: definitions.map(a => a.id === id ? { ...a, ...patch } : a) });
  return <fieldset className="dr-bond-editor dr-attribute-editor" disabled={disabled}><legend>{t("title")}</legend><p className="dr-character-hint">{t("hint")}</p>{!enabled && <p className="dr-bond-note">{immersionText(locale, "paused")}</p>}{!definitions.length && <><p className="dr-character-hint">{t("empty")}</p><button type="button" onClick={() => onSheet({ ...sheet, attributes: starterAttributes(locale) })}>{t("starter")}</button></>}
    {duplicate && <p role="alert" className="dr-bond-note">{t("duplicate")}</p>}{definitions.map((a, index) => <section className="dr-bond-block" key={a.id} aria-label={`${t("title")} ${index + 1}`}><div className="dr-attribute-heading"><label>{t("name")} {index + 1}<input required maxLength={40} value={a.label} ref={input => { input?.setCustomValidity(a.label.trim() && definitions.some(other => other.id !== a.id && other.label.trim().toLocaleLowerCase() === a.label.trim().toLocaleLowerCase()) ? t("duplicate") : ""); }} onChange={event => update(a.id, { label: event.target.value })} /></label><button type="button" aria-label={`${t("remove")} ${index + 1}`} onClick={() => onSheet({ ...sheet, attributes: definitions.filter(item => item.id !== a.id) })}><Trash2 size={16} /></button></div>
      <div className="dr-bond-scores"><label>{t("initial")}<ScoreInput label={`${t("initial")} · ${a.label || index + 1}`} value={a.initial} onChange={initial => update(a.id, { initial })} /></label>{!profileOnly && <label>{t("current")}<ScoreInput label={`${t("current")} · ${a.label || index + 1}`} value={current.values[a.id]!} onChange={value => onState({ ...state, attributes: { ...current, values: { ...current.values, [a.id]: value } } })} /></label>}</div>
      {!profileOnly && <label className="dr-bond-toggle"><span>{t("lock")}</span><input type="checkbox" role="switch" checked={current.locked.includes(a.id)} onChange={event => onState({ ...state, attributes: { ...current, locked: event.target.checked ? [...current.locked.filter(id => id !== a.id), a.id] : current.locked.filter(id => id !== a.id) } })} /></label>}
      <p className="dr-attribute-meaning">{immersionText(locale, attributeBand(a, profileOnly ? a.initial : current.values[a.id]!))}{attributeMeaning(a, profileOnly ? a.initial : current.values[a.id]!) && ` · ${attributeMeaning(a, profileOnly ? a.initial : current.values[a.id]!)}`}</p>
      <details className="dr-attribute-bounds" open={(a.lowAt ?? 30) >= (a.highAt ?? 70) ? true : undefined} onInvalidCapture={event => { event.currentTarget.open = true; }}><summary>{immersionText(locale, "bounds")}</summary><p className="dr-character-hint">{immersionText(locale, "boundsHint")}</p><div className="dr-bond-scores"><label>{immersionText(locale, "lowAt")}<ScoreInput label={`${immersionText(locale, "lowAt")} · ${a.label || index + 1}`} value={a.lowAt ?? 30} error={(a.lowAt ?? 30) >= (a.highAt ?? 70) ? immersionText(locale, "boundsInvalid") : undefined} onChange={lowAt => update(a.id, { lowAt })} /></label><label>{immersionText(locale, "highAt")}<ScoreInput label={`${immersionText(locale, "highAt")} · ${a.label || index + 1}`} value={a.highAt ?? 70} onChange={highAt => update(a.id, { highAt })} /></label></div>{(a.lowAt ?? 30) >= (a.highAt ?? 70) && <p role="alert" className="dr-bond-note">{immersionText(locale, "boundsInvalid")}</p>}</details>
      <label>{t("low")}<textarea aria-label={t("low")} rows={2} maxLength={160} value={a.low} onChange={event => update(a.id, { low: event.target.value })} /></label><label>{t("high")}<textarea aria-label={t("high")} rows={2} maxLength={160} value={a.high} onChange={event => update(a.id, { high: event.target.value })} /></label><label>{t("cap")}<Select aria-label={`${t("cap")} · ${a.label || index + 1}`} value={a.cap} onChange={event => update(a.id, { cap: Number(event.target.value) })}>{[1, 2, 3, 5, 8].map(cap => <option key={cap} value={cap}>{cap}</option>)}{![1, 2, 3, 5, 8].includes(a.cap) && <option value={a.cap}>{a.cap}</option>}</Select></label>
    </section>)}<button type="button" disabled={definitions.length >= 6} onClick={() => onSheet({ ...sheet, attributes: [...definitions, { id: createId("attribute"), label: "", initial: 50, low: "", high: "", cap: 3 }] })}><Plus size={16} />{t("add")}</button><small className="dr-character-hint">{t("editHint")}</small>
    {!profileOnly && <details className="dr-bond-history dr-attribute-history"><summary>{relationshipText(locale, "history")} · {t("title")}</summary>{last?.source === "scene" && <><button type="button" disabled={definitions.some(a => current.values[a.id] !== last.after[a.id])} onClick={() => onState({ ...state, attributes: { ...current, values: Object.fromEntries(definitions.map(a => [a.id, last.before[a.id] ?? a.initial])) } })}>{t("undo")}</button><p className="dr-character-hint">{t("undoHint")}</p></>}{!current.history.length ? <p>{relationshipText(locale, "noHistory")}</p> : <ol>{current.history.map((item, index) => <li key={`${item.at}:${index}`}><strong>{relationshipText(locale, item.source === "manual" ? "manual" : "scene")}</strong><small>{new Intl.DateTimeFormat(locale, { dateStyle: "short", timeStyle: "short" }).format(item.at)}</small>{Object.entries(item.after).filter(([id, value]) => value !== item.before[id]).map(([id, value]) => <p key={id}>{definitions.find(a => a.id === id)?.label ?? id}: {item.before[id] ?? "—"} → {value}</p>)}{item.reason && <p>{item.reason}</p>}{item.quote && <blockquote>{item.quote}</blockquote>}</li>)}</ol>}</details>}
  </fieldset>;
}
