import { Select } from "./Select";
import { useEffect, useId, useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import type { CharacterSheet, CharacterStatus, DeepRoleSettings, Locale, RelationshipProfile, RelationshipState, SceneEntity } from "../../core/types";
import { bondFor, DEFAULT_RELATIONSHIP, relationshipGate, relationshipStage, relationshipState, RELATIONSHIP_PRESETS } from "../../core/relationships";
import { relationshipText, type RelationshipCopyKey } from "../../core/relationship-i18n";
import { createId } from "../../core/id";
import { progressText } from "../../core/progress-i18n";
import { immersionText } from "../../core/immersion-i18n";

export function RelationshipSettings({ settings, onSettings }: { settings: DeepRoleSettings; onSettings: (value: DeepRoleSettings) => void | Promise<void> }) {
  const t = (key: RelationshipCopyKey) => relationshipText(settings.locale, key);
  return <section className="dr-bond-settings"><label className="toggle-row"><span>{t("enabled")}</span><input type="checkbox" role="switch" checked={settings.relationshipsEnabled !== false} onChange={event => void onSettings({ ...settings, relationshipsEnabled: event.target.checked })} /></label><p className="setting-copy">{t("enabledHint")}</p>{!settings.characterSheetsEnabled && <p className="setting-copy">{t("needsCards")}</p>}<label className="dr-bond-field">{t("display")}<Select aria-label={t("display")} value={settings.relationshipDisplay ?? "both"} onChange={event => void onSettings({ ...settings, relationshipDisplay: event.target.value as DeepRoleSettings["relationshipDisplay"] })}>{(["both", "numbers", "stages"] as const).map(value => <option key={value} value={value}>{t(value)}</option>)}</Select></label></section>;
}
export function RelationshipSummary({ locale, person, hero, state, display = "both" }: { locale: Locale; person: SceneEntity; hero?: SceneEntity; state?: CharacterStatus; display?: DeepRoleSettings["relationshipDisplay"] }) {
  const bond = bondFor(person, hero, state); if (!bond) return null;
  const t = (key: RelationshipCopyKey) => relationshipText(locale, key);
  return <span className="dr-bond-summary">{display !== "numbers" && <span>{t(relationshipStage(bond))}</span>}{display !== "stages" && <small>{t("trust")} {bond.trust} · {t("affinity")} {bond.affinity}</small>}</span>;
}
export function RelationshipScores({ locale, value, onChange, disabled = false }: { locale: Locale; value: { trust: number; affinity: number }; onChange: (value: { trust: number; affinity: number }) => void; disabled?: boolean }) {
  const t = (key: RelationshipCopyKey) => relationshipText(locale, key);
  return <div className="dr-bond-scores">{(["trust", "affinity"] as const).map(key => <label key={key}><span>{t(key)} <small>/ 100</small></span><ScoreInput label={t(key)} value={value[key]} disabled={disabled} onChange={next => onChange({ ...value, [key]: next })} /></label>)}</div>;
}
export function ScoreInput({ label, value, disabled, error, onChange }: { label: string; value: number; disabled?: boolean; error?: string; onChange: (value: number) => void }) {
  const [draft, setDraft] = useState(String(value));
  useEffect(() => setDraft(String(value)), [value]);
  return <input type="number" inputMode="numeric" aria-label={label} min={0} max={100} step={1} required ref={input => input?.setCustomValidity(error ?? "")} value={draft} disabled={disabled} onChange={event => { setDraft(event.currentTarget.value); const next = event.currentTarget.valueAsNumber; if (Number.isInteger(next) && next >= 0 && next <= 100) onChange(next); }} onBlur={event => { if (event.currentTarget.value.trim() && Number.isFinite(event.currentTarget.valueAsNumber)) { const next = Math.max(0, Math.min(100, Math.round(event.currentTarget.valueAsNumber))); setDraft(String(next)); onChange(next); } }} />;
}
export function RelationshipPresets({ locale, onChange, disabled }: { locale: Locale; onChange: (value: { trust: number; affinity: number }) => void; disabled?: boolean }) {
  return <label className="dr-bond-field">{relationshipText(locale, "preset")}<Select aria-label={relationshipText(locale, "preset")} value="" disabled={disabled} onChange={event => { if (event.target.value) onChange({ ...RELATIONSHIP_PRESETS[event.target.value as keyof typeof RELATIONSHIP_PRESETS] }); }}><option value="" disabled>—</option>{Object.entries(RELATIONSHIP_PRESETS).map(([key, value]) => <option key={key} value={key}>{relationshipText(locale, key as RelationshipCopyKey)} · {value.trust}/{value.affinity}</option>)}</Select></label>;
}
export function RelationshipEditor(props: { profileOnly?: boolean; locale: Locale; entity: SceneEntity | null; hero?: SceneEntity; sheet: CharacterSheet; state: CharacterStatus; enabled?: boolean; notice?: string; disabled?: boolean; onSheet: (sheet: CharacterSheet) => void; onState: (state: CharacterStatus) => void }) {
  const t = (key: RelationshipCopyKey) => relationshipText(props.locale, key);
  const eventId = useId(); const profile = props.sheet.relationships;
  const bond = !props.profileOnly && profile && props.hero ? relationshipState(profile, props.state.bonds?.[props.hero.id]) : undefined;
  const last = bond?.history[0];
  const setProfile = (value: RelationshipProfile) => props.onSheet({ ...props.sheet, relationships: value });
  const setBond = (value: RelationshipState) => { if (props.hero) props.onState({ ...props.state, bonds: { ...props.state.bonds, [props.hero.id]: value } }); };
  const person = { ...props.entity, id: props.entity?.id ?? "new", characterSheet: props.sheet } as SceneEntity;
  return <fieldset className="dr-bond-editor" disabled={props.disabled}><legend>{t("title")}</legend><p className="dr-character-hint">{t(props.profileOnly ? "profileScope" : "scope")}</p>{props.enabled === false && <p className="dr-bond-note">{t("paused")}</p>}
    <label className="dr-bond-toggle"><span>{t("adult")}</span><input type="checkbox" role="switch" checked={!!props.sheet.adultConfirmed} onChange={event => props.onSheet({ ...props.sheet, adultConfirmed: event.target.checked })} /></label><small className="dr-character-hint">{t("adultHint")}</small>
    {props.sheet.protagonist ? <p>{t("heroHelp")}</p> : <>
      {!profile ? <div className="dr-bond-note"><p>{t("noSetup")}</p><button type="button" onClick={() => setProfile(structuredClone(DEFAULT_RELATIONSHIP))}>{t("configure")}</button></div> : <>
        <label className="dr-bond-toggle"><span>{t("track")}</span><input type="checkbox" role="switch" checked={profile.enabled} onChange={event => setProfile({ ...profile, enabled: event.target.checked })} /></label>
        <section className="dr-bond-block" aria-label={t("initial")}><h3>{t("initial")}</h3><p className="dr-character-hint">{t("initialHint")}</p><RelationshipPresets locale={props.locale} onChange={initial => setProfile({ ...profile, initial })} /><RelationshipScores locale={props.locale} value={profile.initial} onChange={initial => setProfile({ ...profile, initial })} /><label>{t("pace")}<Select aria-label={t("pace")} value={profile.pace} onChange={event => setProfile({ ...profile, pace: event.target.value as RelationshipProfile["pace"] })}>{(["slow", "balanced", "open"] as const).map(value => <option key={value} value={value}>{t(value)}</option>)}</Select></label></section>
        {!props.profileOnly && (bond && props.hero ? <section className="dr-bond-block" aria-label={t("current")}><h3>{t("current")} · {t(relationshipStage(bond))}</h3><p className="dr-character-hint">{relationshipText(props.locale, "withHero", { name: props.hero.name })}</p><RelationshipScores locale={props.locale} value={bond} onChange={scores => setBond({ ...bond, ...scores })} /><label className="dr-bond-toggle"><span>{t("locked")}</span><input type="checkbox" role="switch" checked={bond.locked} onChange={event => setBond({ ...bond, locked: event.target.checked })} /></label><small className="dr-character-hint">{t("lockedHint")}</small>{props.notice && <p role="status" className="dr-bond-note">{t("skipped")}</p>}</section> : <p className="dr-bond-note">{t("noHero")}</p>)}
        <label>{t("boundaries")}<textarea rows={3} maxLength={600} value={profile.boundaries} placeholder={t("boundariesHint")} onChange={event => setProfile({ ...profile, boundaries: event.target.value })} /></label>
        <label>{progressText(props.locale, "reactions")}<textarea aria-label={progressText(props.locale, "reactions")} rows={3} maxLength={600} value={profile.reactions ?? ""} placeholder={progressText(props.locale, "reactionsHint")} onChange={event => setProfile({ ...profile, reactions: event.target.value })} /></label><p className="dr-character-hint">{progressText(props.locale, "relationHint")}</p>
        <details className="dr-stage-behavior"><summary>{immersionText(props.locale, "behavior")}</summary><p className="dr-character-hint">{immersionText(props.locale, "behaviorHint")}</p>{(["guarded", "acquaintance", "trusting", "close"] as const).map(stage => <label key={stage}>{t(stage)}<textarea aria-label={`${immersionText(props.locale, "behavior")} · ${t(stage)}`} rows={2} maxLength={240} value={profile.stageBehavior?.[stage] ?? ""} placeholder={immersionText(props.locale, "behaviorPlaceholder")} onChange={event => setProfile({ ...profile, stageBehavior: { ...profile.stageBehavior, [stage]: event.target.value } })} /></label>)}</details>
        <label className="dr-bond-toggle"><span>{t("romance")}</span><input type="checkbox" role="switch" checked={profile.romance} onChange={event => setProfile({ ...profile, romance: event.target.checked })} /></label><p className="dr-character-hint">{t("consent")}</p>
        {profile.romance && <section className="dr-bond-block"><h3>{t("thresholds")}</h3><div className="dr-bond-scores">{(["trust", "affinity"] as const).map(key => <label key={key}>{t(key === "trust" ? "trustThreshold" : "affinityThreshold")}<ScoreInput label={t(key === "trust" ? "trustThreshold" : "affinityThreshold")} value={profile.thresholds[key]} onChange={value => setProfile({ ...profile, thresholds: { ...profile.thresholds, [key]: value } })} /></label>)}</div>{bond && <p className="dr-bond-note">{t(relationshipGate(person, props.hero, bond))}</p>}</section>}
        <section className="dr-bond-block"><h3>{t("milestones")}</h3><p className="dr-character-hint">{immersionText(props.locale, "eventHint")}</p>{profile.milestones.map((event, index) => <div className="dr-bond-event" key={index}><label htmlFor={eventId + event.id}>{t("eventLabel")} {index + 1}<input id={eventId + event.id} required maxLength={100} value={event.label} placeholder={t("eventPlaceholder")} onChange={e => { const nextId = createId("event"); setProfile({ ...profile, milestones: profile.milestones.map(m => m.id === event.id ? { ...m, id: nextId, label: e.target.value } : m) }); if (bond) setBond({ ...bond, completed: bond.completed.filter(id => id !== event.id) }); }} /></label><button type="button" aria-label={`${t("removeEvent")} ${index + 1}`} onClick={() => { setProfile({ ...profile, milestones: profile.milestones.filter(m => m.id !== event.id) }); if (bond) setBond({ ...bond, completed: bond.completed.filter(id => id !== event.id) }); }}><Trash2 size={16} /></button><label className="dr-bond-toggle"><span>{immersionText(props.locale, "required")}</span><input type="checkbox" role="switch" checked={event.required !== false} onChange={e => setProfile({ ...profile, milestones: profile.milestones.map(m => m.id === event.id ? { ...m, required: e.target.checked } : m) })} /></label>{bond && <label className="dr-bond-toggle"><span>{t("completed")}</span><input type="checkbox" role="switch" checked={bond.completed.includes(event.id)} onChange={e => setBond({ ...bond, completed: e.target.checked ? [...bond.completed.filter(id => id !== event.id), event.id] : bond.completed.filter(id => id !== event.id) })} /></label>}</div>)}<button type="button" disabled={profile.milestones.length >= 8} onClick={() => setProfile({ ...profile, milestones: [...profile.milestones, { id: createId("event"), label: "", required: false }] })}><Plus size={16} />{t("addEvent")}</button><small className="dr-character-hint">{t("eventEditHint")}</small></section>
        {!props.profileOnly && <details className="dr-bond-history"><summary>{t("history")}</summary>{last?.source === "scene" && bond && <><button type="button" disabled={bond.trust !== last.after.trust || bond.affinity !== last.after.affinity} onClick={() => setBond({ ...bond, ...last.before, completed: bond.completed.filter(id => !last.milestones.includes(id)) })}>{progressText(props.locale, "undo")}</button><p className="dr-character-hint">{progressText(props.locale, "undoHint")}</p></>}{!bond?.history.length ? <p>{t("noHistory")}</p> : <ol>{bond.history.map((item, index) => <li key={item.at + ":" + index}><strong>{t(item.source === "manual" ? "manual" : "scene")}</strong><small>{new Intl.DateTimeFormat(props.locale, { dateStyle: "short", timeStyle: "short" }).format(item.at)}</small><p>{t("trust")} {item.before.trust} → {item.after.trust} · {t("affinity")} {item.before.affinity} → {item.after.affinity}</p>{item.reason && <p>{item.reason}</p>}{item.quote && <blockquote>{item.quote}</blockquote>}</li>)}</ol>}</details>}
      </>}
    </>}
  </fieldset>;
}
