import type { Locale } from "./types";

const messages = {
  en: {
    activationHelp: "This is the entry's saved mode, shared by chats using its world. Always: every request. Automatic (called): local matching within the budget. Manual: only after attachment. Chat attachments and exclusions are separate. Changes affect the next request; no message is sent automatically.",
    networkFailed: "The request was interrupted or failed. No result was saved. You can try again.", handoffSaved: "Story state saved. Your draft is untouched. Continue later from Play → Continue your story.", handoffUnavailable: "This story state is missing, locked or its world has changed. Nothing was applied. Reopen the list and try again.", handoffPromptReady: "The recap is ready. A continuation prompt is in the message box; send it when you’re ready.", handoffContinuing: "Continuing in the new chat…",
    sceneChanged: "The chat or world changed while preparing. Nothing was sent. Start again in the current chat.", serviceFailed: "Could not start the request. Nothing was sent. Please try again.",
    remember: "Remember", rememberHelp: "Save a fact or rule in the current world. The map, list and chat use this same record. DeepSeek receives selected records when you send a message.",
    content: "What should stay in memory?", title: "Name (optional)", fact: "Fact", rule: "Rule", note: "For later", save: "Save to lore", close: "Close", draft: "Ask DeepSeek to propose lore", brief: "Describe your world or the rules you want", draftHelp: "Only runs when you press this button. DeepSeek proposes records, but nothing becomes lore until you review and save it. Your chat draft is never overwritten.",
    quickHelp: "Fact: selected when relevant. Rule: included every time. For later: only included when you attach it manually. All three stay in the current world.",
    review: "Review changes", reviewHelp: "Select what to save. You can edit the text before confirming.", reviewCount: "{selected} of {total} selected", reviewNeedsReview: "Needs review", reviewMissingFields: "Fill in the record", reviewDiscardConfirm: "Discard every proposal in this group? Nothing will be added to memory.", reviewDiscardFinal: "Discard all", reviewCancel: "Go back",
    newEntry: "New record", update: "Update record", before: "Before", after: "After", select: "Save this change", saveChanges: "Save selected changes", discard: "Discard these proposals", noChanges: "No new lore facts found. Continue the story and try again later.", analysisSummary: "DeepSeek prepared changes for your memory: {count}. Nothing has been saved; review them in DeepRole.", analysisNoChanges: "No new memory proposals. Memory is unchanged.", invalidServiceResult: "Could not prepare memory suggestions. Nothing was saved — try Update lore again.", undo: "Undo last saved changes", undoHelp: "Restores the last approved batch only if its records have not been edited since. It never overwrites newer work.",
    conflict: "This record changed since analysis, or its world no longer exists. Nothing was overwritten. Reopen the review or run a fresh analysis.", failed: "Could not save. Your text is still here. Please try again.", memoryUpdated: "Memory updated: {count}", memoryButtonHelp: "Starts analysis in DeepSeek. A waiting card appears in chat; you review proposals before saving.",
    issue: "The original record changed or could not be found. Review the text, then leave this proposal out or turn it into a new record. Nothing is saved yet.", asNew: "Use as a new record", emptyChat: "Start a conversation first, or use Remember to write your own lore.", draftProtected: "Your message is still in the chat box. Send it or clear it first.", busy: "DeepSeek is still answering or an analysis is pending. Please wait before starting another.",
    overflow: "Pinned memory exceeds the limit. Remove some pinned records or increase the world’s limit.", omitted: "Some relevant records did not fit the limit.", reset: "Use normal selection", attached: "Included in this chat", excluded: "Not used in this chat", automatic: "Normal selection", inContext: "Included in the next message", notSelected: "Not included in the next message", include: "Include in this chat", exclude: "Leave out of this chat", chatUseTitle: "In this chat", chatUseHelp: "When included, DeepRole adds this record to each message you send to DeepSeek in this chat. It won't appear in the conversation or affect other chats.", chatAnalyze: "Update lore", chatAnalyzeHelp: "DeepSeek reviews this conversation and suggests useful facts for memory. Review suggestions before saving; nothing is added automatically.", memoryUnavailable: "This record is no longer available in the current world. Refresh the list and try again.", vaultLocked: "Unlock your memory vault before changing chat memory.", runtimeHelp: "This changes selection in the current chat only. Always: every message; Automatic: local matching and links; Manual: only when attached. Reference-only links and map positions do not add facts to the chat.", offWorld: "Connect this world to the current chat to change how its memories are used.", mode: "When to include", always: "Always", smart: "Automatic", manual: "Manual", analyze: "Update lore", ready: "Changes are ready", scope: "Current world", saved: "Saved", proposals: "Pending proposals",
  },
  ru: {
    activationHelp: "Это сохранённый режим записи, общий для чатов этого мира. Всегда: в каждом запросе. Автоподбор (called): локальный подбор в пределах лимита. Вручную: после прикрепления. Прикрепления и исключения текущего чата настраиваются отдельно. Изменение действует со следующего запроса; сообщения сами не отправляются.",
    networkFailed: "Запрос прерван или не завершился. Результат не сохранён — можно попробовать ещё раз.", handoffSaved: "Состояние истории сохранено. Ваш черновик остался на месте. Продолжить позже: Игра → Продолжение истории.", handoffUnavailable: "Состояние истории недоступно, сейф закрыт или мир изменился. Ничего не применено — откройте список заново.", handoffPromptReady: "Пересказ готов. Черновик продолжения уже в поле сообщения — отправьте его, когда будете готовы.", handoffContinuing: "Продолжаем историю в новом чате…",
    sceneChanged: "Во время подготовки изменился чат или мир. Ничего не отправлено — запустите команду заново в текущем чате.", serviceFailed: "Не удалось запустить запрос. Ничего не отправлено — попробуйте ещё раз.",
    remember: "Запомнить", rememberHelp: "Сохранить факт или правило в текущем мире. Карта, список и чат используют одну и ту же запись. DeepSeek получает выбранные записи при отправке сообщения.",
    content: "Что нужно оставить в памяти?", title: "Название (необязательно)", fact: "Факт", rule: "Правило", note: "На потом", save: "Сохранить в лор", close: "Закрыть", draft: "Попросить DeepSeek предложить лор", brief: "Опишите свой мир или нужные правила", draftHelp: "Запускается только по этой кнопке. DeepSeek предлагает записи, но они станут лором лишь после проверки и сохранения. Черновик вашего сообщения не перезаписывается.",
    quickHelp: "Факт: подбирается к подходящей сцене. Правило: добавляется каждый раз. На потом: используется только после ручного прикрепления. Всё сохраняется в текущем мире.",
    review: "Проверить изменения", reviewHelp: "Это предложения, ещё не память. Сравните изменения, поправьте текст и сохраните нужное. Можно продолжать игру, пока предложения ждут здесь.", reviewCount: "Выбрано {selected} из {total}", reviewNeedsReview: "Нужна проверка", reviewMissingFields: "Заполните запись", reviewDiscardConfirm: "Отклонить все предложения этой группы? В память ничего не попадёт.", reviewDiscardFinal: "Отклонить все", reviewCancel: "Вернуться",
    newEntry: "Новая запись", update: "Изменение записи", before: "Было", after: "Станет", select: "Сохранить это изменение", saveChanges: "Сохранить выбранное", discard: "Отклонить эти предложения", noChanges: "Новых фактов для лора не найдено. Продолжите сюжет и попробуйте позже.", analysisSummary: "Готово: {count} предложений для памяти. Ничего не сохранено — проверьте их в DeepRole.", analysisNoChanges: "Новых предложений для памяти нет. Лор не менялся.", invalidServiceResult: "Не удалось подготовить предложения памяти. Ничего не сохранено — повторите «Обновить лор».", undo: "Отменить последние изменения", undoHelp: "Возвращает состояние до последнего подтверждённого пакета, если его записи ещё не редактировали. Более свежие изменения не перезаписывает.",
    conflict: "После анализа запись изменилась или её мир удалён. Ничего не перезаписано. Откройте проверку заново или запустите свежий анализ.", failed: "Не удалось сохранить. Ваш текст остался здесь — попробуйте ещё раз.", memoryUpdated: "Память обновлена: {count}", memoryButtonHelp: "Запустит анализ в DeepSeek. В чате появится плашка ожидания, затем вы проверите предложения.",
    issue: "Исходная запись изменилась или не найдена. Проверьте текст, затем пропустите предложение либо превратите его в новую запись. Пока ничего не сохранено.", asNew: "Использовать как новую запись", emptyChat: "Сначала начните разговор или запишите свой лор через «Запомнить».", draftProtected: "В поле чата осталось ваше сообщение. Сначала отправьте или очистите его.", busy: "DeepSeek ещё отвечает или анализ не завершён. Подождите перед новым запуском.",
    overflow: "Закреплённая память превышает лимит. Снимите часть закреплений или увеличьте лимит мира.", omitted: "Часть подходящих записей не поместилась в лимит.", reset: "Вернуть обычный выбор", attached: "Учитывается в этом чате", excluded: "Не учитывается в этом чате", automatic: "Обычный подбор", inContext: "Попадёт в следующее сообщение", notSelected: "Не попадёт в следующее сообщение", include: "Учитывать в этом чате", exclude: "Не учитывать в этом чате", chatUseTitle: "В этом чате", chatUseHelp: "Если включить запись, DeepRole добавит её к каждому следующему сообщению для DeepSeek. В переписке её не будет; в других чатах настройка не изменится.", chatAnalyze: "Обновить лор", chatAnalyzeHelp: "DeepSeek просмотрит переписку и предложит важные факты для памяти. Проверьте предложения перед сохранением — автоматически ничего не добавится.", memoryUnavailable: "Эта запись больше не относится к выбранному миру. Обновите список и попробуйте ещё раз.", vaultLocked: "Сначала разблокируйте хранилище памяти.", runtimeHelp: "Здесь меняется только подбор для текущего чата. Всегда: каждое сообщение; Автоподбор: локальный поиск и связи; Вручную: только после прикрепления. Справочные связи и расположение на карте не добавляют факты в чат.", offWorld: "Подключите этот мир к текущему чату, чтобы менять использование его памяти.", mode: "Когда использовать", always: "Всегда", smart: "Автоподбор", manual: "Вручную", analyze: "Обновить лор", ready: "Изменения готовы", scope: "Текущий мир", saved: "Сохранено", proposals: "Предложения на проверку",
  },
} as const;
export type AssistantKey = keyof typeof messages.en;
export function assistantText(locale: Locale, key: AssistantKey): string { return messages[locale][key]; }
