import type { Locale } from "./types";
const copy = {
 // Activity hints describe waiting, not invented completion percentages.
 ru: { title: "Персонажи из лора", start: "Создать персонажей из лора", hint: "Анкеты, ГГ, характеристики и отношения — по сохранённой истории.", auto: "Подготовить персонажей из лора", autoHint: "Лор будет отправлен в отдельный временный чат DeepSeek. Результат появится для проверки; временный чат удалится.", emptyHint: "В пустом мире подготовка начнётся после добавления лора.", opening: "Открываем временный чат", reading: "Читаем историю", analyzing: "Собираем анкеты и отношения", ready: "Персонажи готовы к проверке", applied: "Персонажи сохранены", cancelled: "Подготовка отменена", error: "Не удалось подготовить персонажей", review: "Проверить персонажей", close: "Закрыть", cancel: "Отменить подготовку", retry: "Повторить", reprepare: "Подготовить заново", cleanupRequired: "Сначала удалите предыдущий временный чат кнопкой ниже.", save: "Сохранить выбранных", hero: "Главный герой", chooseHero: "Выберите главного героя среди выбранных персонажей.", select: "Добавить", estimates: "Числа — оценка DeepSeek по лору. Их можно исправить. Заполненные анкеты и уже сыгранные значения сохраняются.", trust: "Доверие", affinity: "Симпатия", appearance: "Внешность", personality: "Характер", goals: "Цели", background: "О персонаже", attributes: "Характеристики", relationship: "Отношения", condition: "Состояние", evidence: "На основании лора", cleanup: "Удаляем временный чат", cleanupFailed: "Подготовка сохранена, но временный чат удалить не удалось.", cleanupRetry: "Повторить удаление", openChat: "Открыть временный чат", existing: "Дополнит пустые поля", source: "Источников", count: "Персонажей", failed: "Можно повторить подготовку.", loreEmpty: "Сначала добавьте описание истории или записи лора.", large: "Лор больше 220 тыс. символов. Разделите его на отдельные миры для полного разбора.", changed: "Лор изменился после подготовки. Повторите разбор, чтобы сохранить актуальные анкеты.", login: "Войдите в DeepSeek и повторите подготовку.", interrupted: "Подготовка прервана. Сохранённые анкеты не изменились.", busy: "Уже готовятся персонажи другого мира.", ambiguous: "В лоре есть неоднозначные имена. Проверьте карточки и повторите разбор.", heroConflict: "В мире уже отмечен другой главный герой. Измените отметку в его анкете или выберите его здесь." },
 en: { title: "Characters from lore", start: "Create characters from lore", hint: "Profiles, protagonist, attributes and relationships from the saved story.", auto: "Prepare characters from lore", autoHint: "Lore will be sent to a separate temporary DeepSeek chat. You can review the result; the temporary chat will be deleted.", emptyHint: "In an empty world, preparation starts after lore is added.", opening: "Opening a temporary chat", reading: "Reading the story", analyzing: "Preparing profiles and relationships", ready: "Characters are ready to review", applied: "Characters saved", cancelled: "Preparation cancelled", error: "Could not prepare characters", review: "Review characters", close: "Close", cancel: "Cancel preparation", retry: "Retry", reprepare: "Prepare again", cleanupRequired: "Delete the previous temporary chat using the button below first.", save: "Save selected", hero: "Protagonist", chooseHero: "Choose a protagonist from the selected characters.", select: "Include", estimates: "Scores are DeepSeek estimates based on lore. You can edit them. Existing profiles and played values are preserved.", trust: "Trust", affinity: "Affinity", appearance: "Appearance", personality: "Personality", goals: "Goals", background: "Background", attributes: "Attributes", relationship: "Relationships", condition: "Condition", evidence: "Based on lore", cleanup: "Deleting the temporary chat", cleanupFailed: "Preparation is saved, but the temporary chat could not be deleted.", cleanupRetry: "Retry deletion", openChat: "Open temporary chat", existing: "Fills empty fields", source: "Sources", count: "Characters", failed: "You can retry preparation.", loreEmpty: "Add a story description or lore entries first.", large: "Lore exceeds 220,000 characters. Split it into separate worlds for complete analysis.", changed: "Lore changed after preparation. Repeat the analysis to save current profiles.", login: "Sign in to DeepSeek and retry preparation.", interrupted: "Preparation was interrupted. Saved profiles are unchanged.", busy: "Characters for another world are being prepared.", ambiguous: "Some names are ambiguous. Check the profiles and repeat the analysis.", heroConflict: "A different protagonist is already marked in this world. Change that profile or choose them here." },
};
const activity = {
 ru: { move: "Переместить окно подготовки", moveHint: "Потяните за заголовок или используйте стрелки", dock: "Вернуть справа от персонажей", fragment: "Фрагмент лора", finalStep: "Финальный ответ DeepSeek", repairStep: "Исправление формата", waitOpening: "Ждём открытия служебного чата…", waitConnection: "Ожидаем соединение с DeepSeek…", waitService: "DeepSeek ещё отвечает. Можно продолжать играть.", waitFragments: "Ждём подтверждения текущего фрагмента…", waitSources: "Исходный лор остаётся без изменений.", waitProfiles: "Ждём готовые анкеты от DeepSeek…", waitRelationships: "Характеристики и отношения появятся для проверки.", recovered: "Данные персонажей восстановлены из уже полученного ответа", recoveredCode: "Показать полученные данные", refusal: "DeepSeek не предоставил полный ответ. Анкеты не изменились. Можно повторить подготовку." },
 en: { move: "Move preparation window", moveHint: "Drag the heading or use arrow keys", dock: "Return beside Characters", fragment: "Lore fragment", finalStep: "Final DeepSeek reply", repairStep: "Format correction", waitOpening: "Waiting for the service chat to open…", waitConnection: "Waiting for DeepSeek to connect…", waitService: "DeepSeek is still responding. You can keep playing.", waitFragments: "Waiting for this fragment to be acknowledged…", waitSources: "Your original lore stays unchanged.", waitProfiles: "Waiting for complete profiles from DeepSeek…", waitRelationships: "Attributes and relationships will be ready to review.", recovered: "Character data restored from the reply already received", recoveredCode: "Show received data", refusal: "DeepSeek did not provide a complete reply. Profiles are unchanged. You can retry preparation." },
};
const statusCopy = {
 ru: { hide: "Скрыть окно подготовки", showStatus: "Показать подготовку персонажей", cleanupConfirm: "Чат уже удалён", cleanupConfirmHint: "Нажмите, только если удалили временный чат вручную. Это снимет отметку DeepRole; лор, анкеты и аватарки не изменятся.", cleanupBlocked: "Удалите временный чат или, если уже удалили его вручную, нажмите «Чат уже удалён».", cleanupUnavailable: "Служебная вкладка недоступна. Если вы удалили временный чат вручную, нажмите «Чат уже удалён».", preparationActive: "Подготовка ещё идёт. Сначала отмените её, если временный чат уже удалён." },
 en: { hide: "Hide preparation window", showStatus: "Show character preparation", cleanupConfirm: "Chat already deleted", cleanupConfirmHint: "Use only if you manually deleted the temporary chat. This clears DeepRole's reminder; lore, profiles and portraits stay unchanged.", cleanupBlocked: "Delete the temporary chat or, if you already deleted it manually, choose “Chat already deleted”.", cleanupUnavailable: "The service tab is unavailable. If you manually deleted the temporary chat, choose “Chat already deleted”.", preparationActive: "Preparation is still running. Cancel it first if you already deleted the temporary chat." },
};
const chatCopy = {
 ru: { savedCount: "Подготовлено анкет", resume: "Продолжить подготовку", partialHint: "Ответ оборвался. Готовые анкеты сохранены для проверки; можно продолжить подготовку оставшихся.", openMissing: "Адрес временного чата не сохранился. Новый диалог вместо него открывать не будем.", openRemoved: "Временный чат уже отмечен как удалённый. Открывать новый вместо него не будем." },
 en: { savedCount: "Profiles prepared", resume: "Continue preparation", partialHint: "The reply ended early. Finished profiles are saved for review; you can continue preparing the remaining people.", openMissing: "The temporary chat address was not saved. We will not open a new conversation in its place.", openRemoved: "The temporary chat is already marked as deleted. We will not open a new conversation in its place." },
};
export type CastCopyKey = keyof typeof copy.ru | keyof typeof activity.ru | keyof typeof statusCopy.ru | keyof typeof chatCopy.ru;
export const castText = (locale: Locale, key: CastCopyKey): string => key in chatCopy[locale] ? chatCopy[locale][key as keyof typeof chatCopy.ru] : key in statusCopy[locale] ? statusCopy[locale][key as keyof typeof statusCopy.ru] : key in activity[locale] ? activity[locale][key as keyof typeof activity.ru] : copy[locale][key as keyof typeof copy.ru];
export function castError(locale: Locale, code: string): string {
 const key: CastCopyKey = code === "partial-reply" ? "partialHint" : code === "model-refusal" ? "refusal" : code === "cleanup-required" ? "cleanupRequired" : code === "lore-empty" ? "loreEmpty" : code === "world-too-large" ? "large" : code === "lore-changed" ? "changed" : code === "login-required" ? "login" : code === "busy" ? "busy" : code === "ambiguous-name" ? "ambiguous" : code === "hero-conflict" ? "heroConflict" : ["interrupted","tab-closed","user-interrupted","chat-changed","vault-locked"].includes(code) ? "interrupted" : "failed";
 return castText(locale, code === "temporary-chat-address-missing" ? "openMissing" : code === "temporary-chat-removed" ? "openRemoved" : code === "cleanup-required" ? "cleanupBlocked" : code === "cleanup-unavailable" ? "cleanupUnavailable" : code === "preparation-active" ? "preparationActive" : key);
}
