import type { Locale } from "./types";
const copy = {
 ru: { title: "Персонажи из лора", start: "Создать персонажей из лора", hint: "Анкеты, ГГ, характеристики и отношения — по сохранённой истории.", auto: "Подготовить персонажей из лора", autoHint: "Лор будет отправлен в отдельный временный чат DeepSeek. Результат появится для проверки; временный чат удалится.", emptyHint: "В пустом мире подготовка начнётся после добавления лора.", opening: "Открываем временный чат", reading: "Читаем историю", analyzing: "Собираем анкеты и отношения", ready: "Персонажи готовы к проверке", applied: "Персонажи сохранены", cancelled: "Подготовка отменена", error: "Не удалось подготовить персонажей", review: "Проверить персонажей", close: "Закрыть", cancel: "Отменить подготовку", retry: "Повторить", reprepare: "Подготовить заново", cleanupRequired: "Сначала удалите предыдущий временный чат кнопкой ниже.", save: "Сохранить выбранных", hero: "Главный герой", chooseHero: "Выберите главного героя среди выбранных персонажей.", select: "Добавить", estimates: "Числа — оценка DeepSeek по лору. Их можно исправить. Заполненные анкеты и уже сыгранные значения сохраняются.", trust: "Доверие", affinity: "Симпатия", appearance: "Внешность", personality: "Характер", goals: "Цели", background: "О персонаже", attributes: "Характеристики", relationship: "Отношения", condition: "Состояние", evidence: "На основании лора", cleanup: "Удаляем временный чат", cleanupFailed: "Подготовка сохранена, но временный чат удалить не удалось.", cleanupRetry: "Повторить удаление", openChat: "Открыть временный чат", existing: "Дополнит пустые поля", source: "Источников", count: "Персонажей", failed: "Можно повторить подготовку.", loreEmpty: "Сначала добавьте описание истории или записи лора.", large: "Лор больше 220 тыс. символов. Разделите его на отдельные миры для полного разбора.", changed: "Лор изменился после подготовки. Повторите разбор, чтобы сохранить актуальные анкеты.", login: "Войдите в DeepSeek и повторите подготовку.", interrupted: "Подготовка прервана. Сохранённые анкеты не изменились.", busy: "Уже готовятся персонажи другого мира.", ambiguous: "В лоре есть неоднозначные имена. Проверьте карточки и повторите разбор.", heroConflict: "В мире уже отмечен другой главный герой. Измените отметку в его анкете или выберите его здесь." },
 en: { title: "Characters from lore", start: "Create characters from lore", hint: "Profiles, protagonist, attributes and relationships from the saved story.", auto: "Prepare characters from lore", autoHint: "Lore will be sent to a separate temporary DeepSeek chat. You can review the result; the temporary chat will be deleted.", emptyHint: "In an empty world, preparation starts after lore is added.", opening: "Opening a temporary chat", reading: "Reading the story", analyzing: "Preparing profiles and relationships", ready: "Characters are ready to review", applied: "Characters saved", cancelled: "Preparation cancelled", error: "Could not prepare characters", review: "Review characters", close: "Close", cancel: "Cancel preparation", retry: "Retry", reprepare: "Prepare again", cleanupRequired: "Delete the previous temporary chat using the button below first.", save: "Save selected", hero: "Protagonist", chooseHero: "Choose a protagonist from the selected characters.", select: "Include", estimates: "Scores are DeepSeek estimates based on lore. You can edit them. Existing profiles and played values are preserved.", trust: "Trust", affinity: "Affinity", appearance: "Appearance", personality: "Personality", goals: "Goals", background: "Background", attributes: "Attributes", relationship: "Relationships", condition: "Condition", evidence: "Based on lore", cleanup: "Deleting the temporary chat", cleanupFailed: "Preparation is saved, but the temporary chat could not be deleted.", cleanupRetry: "Retry deletion", openChat: "Open temporary chat", existing: "Fills empty fields", source: "Sources", count: "Characters", failed: "You can retry preparation.", loreEmpty: "Add a story description or lore entries first.", large: "Lore exceeds 220,000 characters. Split it into separate worlds for complete analysis.", changed: "Lore changed after preparation. Repeat the analysis to save current profiles.", login: "Sign in to DeepSeek and retry preparation.", interrupted: "Preparation was interrupted. Saved profiles are unchanged.", busy: "Characters for another world are being prepared.", ambiguous: "Some names are ambiguous. Check the profiles and repeat the analysis.", heroConflict: "A different protagonist is already marked in this world. Change that profile or choose them here." },
};
export type CastCopyKey = keyof typeof copy.ru;
export const castText = (locale: Locale, key: CastCopyKey): string => copy[locale][key];
export function castError(locale: Locale, code: string): string {
 const key: CastCopyKey = code === "cleanup-required" ? "cleanupRequired" : code === "lore-empty" ? "loreEmpty" : code === "world-too-large" ? "large" : code === "lore-changed" ? "changed" : code === "login-required" ? "login" : code === "busy" ? "busy" : code === "ambiguous-name" ? "ambiguous" : code === "hero-conflict" ? "heroConflict" : ["interrupted","tab-closed","user-interrupted","chat-changed","vault-locked"].includes(code) ? "interrupted" : "failed";
 return castText(locale, key);
}
