import type { Locale } from "./types";

const guides = {
  ru: {
    title: "Как работает подбор памяти", close: "Закрыть памятку",
    intro: "Перед отправкой DeepRole выбирает подходящие записи и добавляет их к вашему сообщению. Всю библиотеку каждый раз отправлять не нужно.",
    current: "Порог выбранной чувствительности: {threshold} баллов.",
    sections: [
      { title: "Сначала выберите режим", lines: ["Всегда — подключается к каждому сообщению в своём мире, без поиска совпадений.", "Автоподбор — подключается по совпадениям и связям, если хватает лимита памяти.", "Вручную — подключается только после ручного прикрепления."] },
      { title: "С чем сравнивается запись", lines: ["С вашим сообщением и до четырёх последних обычных сообщений чата. Поэтому после имени «Мира» даже короткое «продолжай» может сохранить подбор о ней.", "Учитываются ключи, название, текст и привязки к персонажам. Регистр не важен, «ё» и «е» равнозначны, окончания частично учитываются.", "Это поиск по совпадениям, не понимание смысла ИИ. Синонимы сами не распознаются: добавляйте нужные варианты в ключи."] },
      { title: "Как набираются баллы", lines: ["За каждый совпавший ключ: +4. За ключевую фразу целиком: +8 вместо +4; совпадение отдельного слова фразы даёт +4.", "За каждое совпавшее слово названия: +3, всего до +9. За слово в тексте: +1, всего до +5. Повтор одного слова не увеличивает эти баллы.", "Дополнительные баллы дают распознанное имя в заголовке (+8), привязка к выбранным в «Сцене» персонажам или группам (+12 за каждую, до +36) и к упомянутым персонажам или группам (+8 за каждую, до +16). Одна привязка не считается сразу в обеих группах.", "Важность умножает итог: низкая ×0,85, обычная ×1, высокая ×1,2."] },
      { title: "Когда запись проходит отбор", lines: ["Больше записей: от 4 баллов. Сбалансированно: от 6. Точнее: от 9. Настройка действует для выбранного мира.", "Пример: совпавший ключ (+4) и слово в названии (+3) дают 7 базовых баллов. При обычной важности этого достаточно для сбалансированного режима — если запись помещается в лимит.", "Связь с режимом «Подбирать вместе» может дополнительно подключить соседнюю запись с автоподбором без прохождения обычного порога. Только на один шаг, не по бесконечной цепочке, и в пределах лимита."] },
      { title: "Почему подходящая запись не подключилась", lines: ["Проверьте: выбран ли нужный мир, включены ли запись и её книга, не исключили ли вы запись вручную, достаточно ли совпадений.", "Сначала идут вручную прикреплённые записи и «Всегда», затем автоподбор по баллам. При равных баллах выше стоит недавно изменённая запись. Длинная запись может не поместиться, а короткая — пройти.", "Лимит учитывает полный текст, служебные пояснения и связи. Анкеты персонажей тоже занимают часть бюджета. «Всегда» и ручное прикрепление могут превысить лимит."] },
      { title: "Что получает DeepSeek", lines: ["Названия и полный текст выбранных записей, а не только совпавшие слова. Ключи нужны для поиска. Подбор пересчитывается перед отправкой; кнопка «Контекст» показывает выбранную память.", "Запись, не выбранная сейчас, могла попасть в предыдущие сообщения. DeepRole не стирает историю DeepSeek и не гарантирует, что модель всегда правильно использует память.", "Нужно подключить факт наверняка? Прикрепите его вручную для этого чата. Для постоянного правила используйте «Всегда». Для автоподбора добавьте конкретные имена, места и варианты названий в ключи."] },
    ],
  },
  en: {
    title: "How memory selection works", close: "Close guide",
    intro: "Before sending, DeepRole selects relevant records and adds them to your message. There is no need to send your entire library every time.",
    current: "Your selected sensitivity threshold: {threshold} points.",
    sections: [
      { title: "Start with the record’s mode", lines: ["Always — included in its own world without checking for matches.", "Automatic — included through matches and links when the memory budget allows.", "Manual — included only when you attach it manually."] },
      { title: "What gets compared", lines: ["Your message and up to four recent ordinary chat messages. After mentioning Mira, even a short “continue” can keep records about her relevant.", "Keywords, title, text and character links are checked. Matching ignores case, treats Russian ё and е alike, and partly handles word endings.", "This is matching, not AI understanding of meaning. Synonyms are not recognized automatically: add useful alternatives to your keywords."] },
      { title: "How points add up", lines: ["Each matching keyword: +4. An entire keyword phrase: +8 instead of +4; a matching word within that phrase gives +4.", "Each matching title word: +3, up to +9 total. Each matching body word: +1, up to +5 total. Repeating a word does not increase these points.", "Extra points come from a recognized name in the title (+8), links to characters or groups selected in Scene (+12 each, up to +36), and links to mentioned characters or groups (+8 each, up to +16). A link is not counted in both groups.", "Priority multiplies the result: low ×0.85, normal ×1, high ×1.2."] },
      { title: "When a record qualifies", lines: ["More records: at least 4 points. Balanced: at least 6. More precise: at least 9. The setting applies to the selected world.", "Example: a keyword (+4) and a title word (+3) give 7 base points. With normal priority, that qualifies for Balanced — provided the record fits the budget.", "A link set to “Select together” can additionally include a neighboring Automatic record without the usual matching threshold. This goes only one hop, not through an endless chain, and must fit the budget."] },
      { title: "Why a relevant record may be missing", lines: ["Check the selected world, whether the record and its book are enabled, whether you excluded the record manually, and whether it has enough matches.", "Manually attached records and Always come first, then Automatic records ranked by points. Ties favor recently edited records. A long record may not fit while a shorter one does.", "The budget includes full text, instructions and links. Character profiles also use part of it. Always and manual attachments can exceed the budget."] },
      { title: "What DeepSeek receives", lines: ["The titles and full text of selected records, not just matching words. Keywords are for searching. Selection is recalculated before sending; the Context button shows the selected memory.", "A record not selected now may already be in earlier messages. DeepRole does not erase DeepSeek’s history or guarantee that the model always uses memory correctly.", "Need to include a fact reliably? Attach it manually for this chat. Use Always for a lasting rule. For Automatic, add specific names, places and alternative names to the keywords."] },
    ],
  },
};

export const memoryGuide = (locale: Locale) => guides[locale];
